### ISSUE TITLE
Downloading datasets via torchvision is not working after hooking

### ISSUE THREAD

**Issue by Ogofo** [OpenMined/PySyft#1647]
Hey, please see the attached code.

After hooking torch, the torchvision method to download the MNIST Dataset fails. I can only assume that this is an unintended behavior. After hooking the functionality of torch/torchvision methods should be guaranteed. 

I will work on this issue in the future. 

```
>>> import torchvision
>>> import syft as sy
>>> from syft.core.frameworks.torch import TorchHook
>>> from syft.core.workers import VirtualWorker, SocketWorker
>>> hook = TorchHook(local_worker=SocketWorker(id=1, port=8290, is_pointer=False, is_client_worker=False))
Starting Socket Worker...
Ready to receive commands...
>>> transform = torchvision.transforms.Compose([torchvision.transforms.ToTensor(), torchvision.transforms.Normalize((0.1307,), (0.3081,))])
>>> root = "./data"
>>> train_set = torchvision.datasets.MNIST(root=root, transform=transform, download=True)
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Processing...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Philipp/anaconda3/envs/pysyft-dev/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/datasets/mnist.py", line 45, in __init__
  File "/Users/Philipp/anaconda3/envs/pysyft-dev/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/datasets/mnist.py", line 135, in download
  File "/Users/Philipp/anaconda3/envs/pysyft-dev/lib/python3.6/site-packages/torch/serialization.py", line 135, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/Users/Philipp/anaconda3/envs/pysyft-dev/lib/python3.6/site-packages/torch/serialization.py", line 117, in _with_file_like
    return body(f)
  File "/Users/Philipp/anaconda3/envs/pysyft-dev/lib/python3.6/site-packages/torch/serialization.py", line 135, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/Users/Philipp/anaconda3/envs/pysyft-dev/lib/python3.6/site-packages/torch/serialization.py", line 198, in _save
    pickler.dump(obj)
  File "/Users/Philipp/anaconda3/envs/pysyft-dev/lib/python3.6/site-packages/torch/tensor.py", line 131, in __reduce__
    args = self.__getstate__()
  File "/Users/Philipp/PySyft/syft/core/frameworks/torch/hook.py", line 467, in _execute_method_call
    return worker._execute_call(attr, self, *args, **kwargs)
  File "/Users/Philipp/PySyft/syft/core/workers/base.py", line 1061, in _execute_call
    wrapper = torch_utils.wrap_command(result)
  File "/Users/Philipp/PySyft/syft/core/frameworks/torch/utils.py", line 292, in wrap_command
    return type(obj)([wrap_command(o) for o in obj])
  File "/Users/Philipp/PySyft/syft/core/frameworks/torch/utils.py", line 292, in <listcomp>
    return type(obj)([wrap_command(o) for o in obj])
  File "/Users/Philipp/PySyft/syft/core/frameworks/torch/utils.py", line 273, in wrap_command
    bind_tensor_nodes(wrapper, obj)
  File "/Users/Philipp/PySyft/syft/core/frameworks/torch/utils.py", line 258, in bind_tensor_nodes
    wrapper.child = child_obj
AttributeError: 'tuple' object has no attribute 'child'
```

**Comment by iamtrask** [comment]
Great find!
