### ISSUE TITLE
.get() operation failed

### ISSUE THREAD

**Issue by xuebao24** [OpenMined/PySyft#1919]
My version is
PySyft-dev
Python 3.6.5
Pytorch '1.0.0'
I did the Tutorial Section 1.1 on page https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%201%20-%20The%20Basic%20Tools%20of%20Private%20Deep%20Learning.ipynb

The same code.

import syft as sy
from syft.frameworks.torch.tensors.interpreters import PointerTensor
from syft.frameworks.torch.tensors.decorators import LoggingTensor
import sys
import torch
hook = sy.TorchHook(torch)
from torch.nn import Parameter
import torch.nn as nn
import torch.nn.functional as F

bob = sy.VirtualWorker(hook, id="bob")
x=torch.tensor([1,2,3,4,5])
y=torch.tensor([1,1,1,1,1])
x_ptr=x.send(bob)
y_ptr=y.send(bob)
print(bob._objects)
z=x_ptr+x_ptr
print(z)
print(bob._objects)
print(x_ptr)
x_ptr.get()
print(y_ptr)
y_ptr.get()
z.get()
print(bob._objects)

When I do 'z.get()', errors shows below while bob._objects still has tensor z with the same number.

Error log:

Traceback (most recent call last):

  File "<ipython-input-4-11b60d6ede25>", line 1, in <module>
    runfile('D:/my_program/python/syft/start_test/test_start.py', wdir='D:/my_program/python/syft/start_test')

  File "C:\Program_Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Program_Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/my_program/python/syft/start_test/test_start.py", line 52, in <module>
    z.get()

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 419, in get
    tensor = self.child.get(*args, **kwargs)

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\pointer.py", line 209, in get
    tensor = self.owner.request_obj(self.id_at_location, self.location)

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\workers\base.py", line 455, in request_obj
    obj = self.send_msg(MSGTYPE.OBJ_REQ, obj_id, location)

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\workers\base.py", line 148, in send_msg
    bin_response = self._send_msg(bin_message, location)

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\workers\virtual.py", line 6, in _send_msg
    return location._recv_msg(message)

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\workers\virtual.py", line 9, in _recv_msg
    return self.recv_msg(message)

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\workers\base.py", line 179, in recv_msg
    response = self._message_router[msg_type](contents)

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\workers\base.py", line 381, in respond_to_obj_req
    obj = self.get_obj(obj_id)

  File "C:\Program_Files\Anaconda3\lib\site-packages\syft\workers\base.py", line 362, in get_obj
    raise KeyError(msg)

KeyError: 'Tensor "16217007849" not found on worker "bob"!!! You just tried to interact with an object ID:16217007849 on worker bob which does not exist!!! Use .send() and .get() on all your tensors to make sure they\'reon the same machines. If you think this tensor does exist, check the ._objects dictionaryon the worker and see for yourself!!! The most common reason this error happens is because someone calls.get() on the object\'s pointer without realizing it (which deletes the remote object and sends it to the pointer). Check your code to make sure you haven\'t already called .get() on this pointer!!!'

**Comment by LaRiffle** [comment]
Does the code run when it is in the notebook?

**Comment by iamtrask** [comment]
This is almost certainly because the VirtualWorker was created twice.

**Comment by xuebao24** [comment]
> This is almost certainly because the VirtualWorker was created twice.

Can you tell me more? I just create bob once by 'bob = sy.VirtualWorker(hook, id="bob")'. Where is the other one? Or can you tell me the right case?
Thank you!

**Comment by xuebao24** [comment]
> Does the code run when it is in the notebook?

I run it in my spyder.

**Comment by xuebao24** [comment]
I saw what happened. This happened just because I runed it twice on my spyder. Maybe this was what iamtrask said 'the VirtualWorker was created twice'.
This program can only run once on your python or restart it!!
Thank you all for help!
