### ISSUE TITLE
Problem at encrypted evaluation with remote workers

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PySyft#2081]
When I try to implement an encrypted evaluation application using remote workers, I am experiencing the following problems: 

> --- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run_websocket_server.py", line 48, in <module>
    server = start_proc(WebsocketServerWorker, kwargs)
  File "run_websocket_server.py", line 20, in start_proc
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_websocket_server.py", line 17, in target
    server.start()
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/workers/websocket_server.py", line 125, in start
    asyncio.get_event_loop().run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/workers/websocket_server.py", line 92, in _producer_handler
    response = self.recv_msg(message)
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/workers/base.py", line 228, in recv_msg
    (msg_type, contents) = sy.serde.deserialize(bin_message, worker=self)
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/serde.py", line 151, in deserialize
    return _detail(worker, simple_objects)
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/serde.py", line 1227, in _detail
    return detailers[obj[0]](worker, obj[1])
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/serde.py", line 612, in _detail_collection_tuple
    pieces.append(_detail(worker, part))
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/serde.py", line 1227, in _detail
    return detailers[obj[0]](worker, obj[1])
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/serde.py", line 426, in _detail_torch_tensor
    chain = _detail(worker, chain)
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/serde.py", line 1227, in _detail
    return detailers[obj[0]](worker, obj[1])
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/serde.py", line 1014, in _detail_additive_shared_tensor
    owner=worker, id=tensor_id, field=field, crypto_provider=worker.get_worker(crypto_provider)
  File "/home/ionesio/workspace/tcc/venv/lib/python3.6/site-packages/syft-0.1.12a1-py3.6.egg/syft/workers/base.py", line 594, in get_worker
    logging.warning("Worker", self.id, "couldn't recognize worker", id_or_worker)
Message: 'Worker'
Arguments: ('alice', "couldn't recognize worker", 'crypto_provider')

Apparently, workers are failing to communicate / recognize.

When I replace remote workers with virtual workers, the application works perfectly.

Workers Manager application: https://hastebin.com/ruxuqejabi.py
Start remote workers app: https://hastebin.com/koxukoqoxa.makefile
Web socket server: https://hastebin.com/eciviwijib.py

**Comment by mari-linhares** [comment]
Hey @IonesioJunior, 

I'll have a look at this!

**Comment by mari-linhares** [comment]
@IonesioJunior, I've just tried using the `dev` branch and it works. Can you try again with the most updated version of `dev`?

**Comment by IonesioJunior** [comment]
My current settings:
syft == 0.1.12a1
Python == 3.6.7
torch == 1.0.1.post2

The error still persists with these settings, but discarding the possibility of a bug has lessened my effort to find the problem. I believe it's something related to the multiple versions of python / libraries that I use on my machine. I'll dig deeper.
Thank you anyway  :smiley:.
