### ISSUE TITLE
Demo Part 2 Failed

### ISSUE THREAD

**Issue by liaoj12** [OpenMined/PySyft#2135]
Hi,
I just tried the part 2 example here, and it didn't work when calling the second train() and the error message is:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in train
  File "~/anaconda3/lib/python3.6/site-packages/syft-0.1.14a1-py3.6.egg/syft/frameworks/torch/hook.py", line 929, in module_send_
  File "~/anaconda3/lib/python3.6/site-packages/syft-0.1.14a1-py3.6.egg/syft/frameworks/torch/tensors/interpreters/native.py", line 330, in send_
  File "~/anaconda3/lib/python3.6/site-packages/syft-0.1.14a1-py3.6.egg/syft/frameworks/torch/tensors/interpreters/native.py", line 279, in send
RuntimeError: set_storage is not allowed on Tensor created from .data or .detach()

System info:
OS: Ubuntu 18.04.1 LTS
python version:  3.6.5 :: Anaconda, Inc.
pytorch version: 1.1.0

**Comment by liaoj12** [comment]
Ok, downgrading pytorch back to version 1.0.0 works....
