### ISSUE TITLE
websockets-example-MNIST 

### ISSUE THREAD

**Issue by andreaBelmont** [OpenMined/PySyft#2258]

**Comment by andreaBelmont** [comment]
Error while running websockets example on my macbook pro

```
python ./run_websocket_client.py
Traceback (most recent call last):
  File "./run_websocket_client.py", line 273, in <module>
    main()
  File "./run_websocket_client.py", line 211, in main
    alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/workers/websocket_client.py", line 57, in __init__
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websocket/_http.py", line 197, in _open_socket
    raise err
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
```


```

Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

Python 3.7.3 (default, Jun  8 2019, 16:41:03)

In [2]: torch.__version__
Out[2]: '1.1.0'


```

**Comment by DanyEle** [comment]
`    alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket)
`
This cannot work. You need to specify a valid host for websockets. Supposing you're running this example with local workers, you may want to use:

`
kwargs_websocket_alice = {"host": "127.0.0.1", "hook": hook}
alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket_alice)
`
Alternatively, if you want to make use of virtual workers- which are not actually web sockets - the following should suffice:
`    alice = sy.VirtualWorker(hook, id="alice")    `
``

**Comment by andreaBelmont** [comment]
Hello DanyEle, thanks for your answer but I am still confused. 

I am running the examples as they are provided in 

`https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/advanced/websockets-example-MNIST/README.md
`

How am I supposed to run the python commands while running both server and client on the same machine?

I have tried (in two distinct bash shells):

`>> python run_websocket_server.py --host 127.0.0.1`

and

`>> python run_websocket_client.py`

and I get 

`ConnectionRefusedError: [Errno 61] Connection refused`

What am I doing wrong?

**Comment by DanyEle** [comment]
You still need to specify the port and ID of the worker. For example for Alice:

  python3 run_websocket_server.py --host 127.0.0.1 --port 8777 --id alice

**Comment by andreaBelmont** [comment]
OK, I think I go that part now. 
But I am now getting a different error though when running the client, which also crashes the servers:

**Error on the client side**

```
Traceback (most recent call last):
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/frameworks/torch/hook/hook_args.py", line 145, in hook_function_args
KeyError: 'torch.as_tensor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_websocket_client.py", line 273, in <module>
    main()
  File "run_websocket_client.py", line 233, in main
    ).federate(tuple(workers)),
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/frameworks/torch/federated/dataset.py", line 161, in dataset_federate
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 95, in __getitem__
    img = self.transform(img)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 164, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 206, in normalize
    mean = torch.as_tensor(mean, dtype=torch.float32, device=tensor.device)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/frameworks/torch/hook/hook.py", line 708, in overloaded_func
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/frameworks/torch/tensors/interpreters/native.py", line 199, in handle_func_command
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/frameworks/torch/hook/hook_args.py", line 152, in hook_function_args
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/frameworks/torch/hook/hook_args.py", line 182, in build_hook_args_function
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/frameworks/torch/hook/hook_args.py", line 411, in build_get_tensor_type
IndexError: list index out of range
```

**Error on the Server side**

```
python start_websocket_servers.py
Starting server for Alice
Starting server for Bob
Starting server for Charlie
 acortis@Jeeg   ~/my_codes/testbed/PySyft/examples/tutorials/advanced/websockets-example-MNIST     dev    ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._consumer_handler() done, defined at /Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/workers/websocket_server.py:74> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/Users/acortis/myERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._consumer_handler() done, defined at /Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/workers/websocket_server.py:74> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/Users/acortis/.pyenv/versions/3.7.3/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/workers/websocket_server.py", line 84, in _consumer_handler
    msg = await websocket.recv()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._consumer_handler() done, defined at /Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/workers/websocket_server.py:74> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/Users/acortis/.pyenv/versions/3.7.3/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/workers/websocket_server.py", line 84, in _consumer_handler
    msg = await websocket.recv()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/Users/acortis/.pyenv/versions/3.7.3/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/workers/websocket_server.py", line 84, in _consumer_handler
    msg = await websocket.recv()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
>....
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/Users/acortis/.pyenv/versions/3.7.3/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/syft-0.1.17-py3.7.egg/syft/workers/websocket_server.py", line 84, in _consumer_handler
    msg = await websocket.recv()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/Users/acortis/my_codes/testbed/PySyft/.env/lib/python3.7/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
zsh: parse error near `)'
```

**Comment by DanyEle** [comment]
I noticed two more weird things in your configuration:

- You are using Python 3.7.3 --> Try using Python3.6 instead. I always run PySyft on Python 3.6.7, as its README file suggest
- You are using Pytorch 1.1.0 --> Try using Pytorch 1.0.1 instead. I don't think PySyft supports PyTorch 1.1, yet, although there are plans to port it to that version.

**Comment by andreaBelmont** [comment]
A couple of remarks: the [readme file](https://github.com/OpenMined/PySyft) clearly states 

> PySyft supports Python >= 3.6 and PyTorch 1.1.0

Anyways, I went ahead and tried what you suggest, that is python 3.6.7, torch=1.0.1, and torchvision=0.2.2, and still does not work. 

Any further suggestions are very much appreciated. Thanks

**Comment by LaRiffle** [comment]
Hi, thanks for reporting this error,
I believe the error was first in the client side to due `mean = torch.as_tensor(mean, dtype=torch.float32, device=tensor.device)`.
This a bug due to upgrading to torchvision 0.3, which was fixed in the dev branch yesterday. If you use directly the source code I'd recommend pulling and retrying you shouldn't have this error anymore (at least not this one). Alternatively check that you have indeed downgraded to torchvision to 0.2.2 (in which the line `mean = torch.as_tensor(mean, dtype=torch.float32, device=tensor.device)` doesn't exist).
So if you can manage to do one of these changes and report how it goes, I'd love to help further!

One last thing, indeed PySyft supports PyTorch 1.1.0 even if there are some bugs like this one that we try to solve as quickly as possible.

**Comment by LaRiffle** [comment]
This should be now fixed with #2266

**Comment by ProfXGiter** [comment]
ENV: linux, python3.6.8, pysyft==0.1.13a1, torch==1.0.1, torchvision==0.2.2

I run the lines:
python3 run_websocket_server.py --host 127.0.0.1 --port 8777 --id alice
python3 run_websocket_client.py

It shows the bug:
KeyError: (wrapper)>[PointerTensor | me:some series of numbers -> alice:some series of number]

**Comment by chenglinfeng** [comment]
change "host" to your local address like "192.168.x.x" (not 127.0.0.1), it works on my machine.
