### ISSUE TITLE
PySyft Installation error: Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by zouininaS** [OpenMined/PySyft#2704]
Hello,
I am new to PySyft I am following the tutorial on Udacity but I have this error I looked in other forums but unfortunately I couldn't solve it,
Would you help me?
Thank you,

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~/anaconda3/lib/python3.7/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~/anaconda3/lib/python3.7/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /users/zouinina/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-0129e7cb4d6c> in <module>
----> 1 from syft.frameworks.torch.differential_privacy import pate

~/anaconda3/lib/python3.7/site-packages/syft/__init__.py in <module>
      6 # We load these modules first so that syft knows which are available
      7 from syft import dependency_check
----> 8 from syft import frameworks  # Triggers registration of any available frameworks
      9 
     10 # Major imports

~/anaconda3/lib/python3.7/site-packages/syft/frameworks/__init__.py in <module>
     12 
     13 if dependency_check.tfe_available:
---> 14     from syft.frameworks import keras
     15 
     16     __all__.append("keras")

~/anaconda3/lib/python3.7/site-packages/syft/frameworks/keras/__init__.py in <module>
      2 
      3 if syft.dependency_check.tfe_available:
----> 4     from syft.frameworks.keras import layers
      5     from syft.frameworks.keras import model
      6     from syft.frameworks.keras.hook import KerasHook

~/anaconda3/lib/python3.7/site-packages/syft/frameworks/keras/layers/__init__.py in <module>
----> 1 from syft.frameworks.keras.layers.constructor import add_constructor_registration
      2 from syft.frameworks.keras.layers.constructor import filter_layers
      3 
      4 __all__ = ["add_constructor_registration", "filter_layers"]

~/anaconda3/lib/python3.7/site-packages/syft/frameworks/keras/layers/constructor.py in <module>
      3 import re
      4 
----> 5 import tf_encrypted as tfe
      6 
      7 

~/anaconda3/lib/python3.7/site-packages/tf_encrypted/__init__.py in <module>
      3 from typing import Optional, Any
      4 import inspect
----> 5 import tensorflow as tf
      6 
      7 from .config import Config

~/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py in <module>
     26 
     27 # pylint: disable=g-bad-import-order
---> 28 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     29 from tensorflow.python.tools import module_util as _module_util
     30 

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/users/zouinina/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/users/zouinina/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/users/zouinina/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/users/zouinina/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/users/zouinina/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /users/zouinina/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by steph-en-m** [comment]
@zouininaS could you specify what you were trying to do when you got this error or which part of the tutorial this error occurred?? Thanks

**Comment by zouininaS** [comment]
When I want to call PATE here:

from syft.frameworks.torch.differential_privacy import pate
Thank you for your answer (I am working on ubuntu)

**Comment by steph-en-m** [comment]
@zouininaS try downgrading python to 3.6 in conda your environment.i.e ```conda activate <your env>``` then ```conda install python=3.6```
