### ISSUE TITLE
Index out of range when running training at VirtualWorker

### ISSUE THREAD

**Issue by JpMCarrilho** [OpenMined/PySyft#2719]
**Describe the bug**
I'm trying to run this https://github.com/williamleif/graphsage-simple in a simple federated setting (sending it to a virtual worker and running the training at him), but I get raised **RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:193** .

As I'm using Python3, there were some minor changes in the _model.py_ I had to make, to run the implementation.
1. Clone the repo from me. (Simple python3 changes made)
https://github.com/JpMCarrilho/GraphSAGE
2. Uncomment syft changes I made in _run_cora()_ function:
           1. Lines 68,69,70 hook and virtual workers
           2. line 87 , _.send(bob)_
3. run model.py file from repo root folder _python -m graphsage.model_

**Expected behavior**
If I don't send the model, to the VirtualWorker, training occurs perfectly, so I don't believe this is a Index problem

**Desktop:**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
Syft: 0.1.26a1
Torch: 1.1.0
In #2260, @LaRiffle sad this was a torchvision 0.3.0 related problem, exactly the version i'm using.

I'm new in PySyft so this may be just a foolish mistake. I've already encountered this error in another implementation of my own but didn't have the time to look more into it.

**Comment by LaRiffle** [comment]
Hey thanks for reporting,
Would you mind adding the stacktrace to this issue?
This might help us to provide help without having to launch the whole project :)

**Comment by JpMCarrilho** [comment]
Sure!
`WARNING:tf_encrypted:Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
WARNING:tensorflow:From /home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

/home/jpmc/GraphSAGE-simple/graphsage/encoders.py:31: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(self.weight)
/home/jpmc/GraphSAGE-simple/graphsage/model.py:29: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(self.weight)
Traceback (most recent call last):
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 302, in handle_func_command
    cmd, args, kwargs, return_args_type=True
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 194, in unwrap_args_from_function
    new_args = args_hook_function(args)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 380, in <lambda>
    return lambda x: f(lambdas, x)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 568, in five_fold
    lambdas[1](args[1], **kwargs),
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 358, in <lambda>
    else lambda i: forward_func[type(i)](i)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 58, in <lambda>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 58, in <genexpr>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
syft.exceptions.PureFrameworkTensorFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jpmc/GraphSAGE-simple/graphsage/model.py", line 186, in <module>
    run_cora()
  File "/home/jpmc/GraphSAGE-simple/graphsage/model.py", line 102, in run_cora
    Variable(torch.LongTensor(labels[np.array(batch_nodes)])))
  File "/home/jpmc/GraphSAGE-simple/graphsage/model.py", line 37, in loss
    scores = self.forward(nodes)
  File "/home/jpmc/GraphSAGE-simple/graphsage/model.py", line 32, in forward
    embeds = self.enc(nodes)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jpmc/GraphSAGE-simple/graphsage/encoders.py", line 40, in forward
    self.num_sample)
  File "/home/jpmc/GraphSAGE-simple/graphsage/aggregators.py", line 61, in forward
    embed_matrix = self.features(torch.LongTensor(unique_nodes_list))
  File "/home/jpmc/GraphSAGE-simple/graphsage/model.py", line 81, in <lambda>
    agg2 = MeanAggregator(lambda nodes : enc1(nodes).t(), cuda=False)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jpmc/GraphSAGE-simple/graphsage/encoders.py", line 40, in forward
    self.num_sample)
  File "/home/jpmc/GraphSAGE-simple/graphsage/aggregators.py", line 61, in forward
    embed_matrix = self.features(torch.LongTensor(unique_nodes_list))
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 117, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/hook.py", line 413, in overloaded_func
    response = handle_func_command(command)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 338, in handle_func_command
    response = eval(cmd)(*args, **kwargs)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/hook.py", line 413, in overloaded_func
    response = handle_func_command(command)
  File "/home/jpmc/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 338, in handle_func_command
    response = eval(cmd)(*args, **kwargs)
RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:193`
