### ISSUE TITLE
Error in dependency_check.py

### ISSUE THREAD

**Issue by klize** [OpenMined/PySyft#2829]
I got some errors while running some examples.
My OS is Window 10 and Ubuntu 18.04,
I used miniconda on windows and venv for the latter, and  both uses python 3.6.x

I checked the library and figured it out that 'util' is another submodule of 'importlib', that is, not defined as an attribute in `__init__.py` in importlib.

So this lead me to here to say, 
```python
import importlib.util
```
must be added to 'dependency_check.py'
Another guess is something deprecated in `FrozedImporter` of `importlib._bootstrap` is used

If not, what am i supposed to fix this error ?
```bash
Traceback (most recent call last):
  File "server_ex.py", line 1, in <module>
    import syft as sy
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\xxx\AppData\Local\Continuum\miniconda3\envs\pysyftex\lib\site-packages\syft-0.2.0a2-py3.6.egg\syft\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\xxx\AppData\Local\Continuum\miniconda3\envs\pysyftex\lib\site-packages\syft-0.2.0a2-py3.6.egg\syft\dependency_check.py", line 18, in <module>
AttributeError: module 'importlib' has no attribute 'util'
```

**Comment by AlanAboudib** [comment]
Thank you @klize for reporting. I could reproduce the issue on an archlinux system, with python 3.6 in miniconda. 

I got the same error after installing `pip install syft` and importing `import syft`. Is anyone aware of this bug @LaRiffle @iamtrask ?

**Comment by karlhigley** [comment]
We just merged [a fix](https://github.com/OpenMined/PySyft/pull/2908) for this yesterday and haven't released a new version yet.

**Comment by AlanAboudib** [comment]
> We just merged [a fix](https://github.com/OpenMined/PySyft/pull/2908) for this yesterday and haven't released a new version yet.

Awesome. That is good to know. I think we can close this issue?
