### ISSUE TITLE
error in tf.keras.layers.DepthwiseConv2D 

### ISSUE THREAD

**Issue by elk-cloner** [OpenMined/PySyft#2853]
**Describe the bug**
i want to use tf.keras.layers.DepthwiseConv2D() but always get this error:

> Traceback (most recent call last):
  File "...../kerasNN.py", line 63, in <module>
    main()
  File "...../kerasNN.py", line 51, in main
    model.add(tf.keras.layers.DepthwiseConv2D(3))
  File "...../anaconda3/envs/pysyft/lib/python3.6/site-packages/syft/frameworks/keras/layers/constructor.py", line 18, in syft_keras_constructor
    self._native_keras_constructor(*args, **kwargs)
  File "...../anaconda3/envs/pysyft/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 1777, in __init__
    **kwargs)
  File "...../anaconda3/envs/pysyft/lib/python3.6/site-packages/syft/frameworks/keras/layers/constructor.py", line 18, in syft_keras_constructor
    self._native_keras_constructor(*args, **kwargs)
  File "....../anaconda3/envs/pysyft/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 1777, in __init__
    **kwargs)
TypeError: __init__() got multiple values for keyword argument 'filters'
Process finished with exit code 1

**To Reproduce**
```
import tensorflow as tf
import syft as sy
hook = sy.KerasHook(tf.keras)
model = tf.keras.Sequential()
model.add(tf.keras.layers.DepthwiseConv2D(3))
print(model.summary())
```

**Expected behavior**
create a model with one DepthwiseConv2D layer
  
**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - syft==0.2.0a2
 - tensorflow==1.15.0

**Comment by aditya-malte** [comment]
Hi,
Could you describe the installation process that you followed? Since there seem to be so many variations, and hence I am facing bugs
Thank you

**Comment by elk-cloner** [comment]
i exactly followed installation process in README.md file.
```
conda create -n pysyft python=3.6
conda activate pysyft
conda install jupyter notebook
pip install syft[udacity]
```
i explicitly added 

> python=3.6

because python=3 install python3.8 and there is no pytorch or tensorflow version compatible with python3.8
