### ISSUE TITLE
add syft to conda-forge

### ISSUE THREAD

**Issue by systemshift** [OpenMined/PySyft#2911]
**Describe the bug**
related to #2885
trying to make a recipe file to add syft package to conda-forge, some error is showing related to `setup.py`

**To Reproduce**
run `conda skeleton pypi syft`

**output**
```
Warning, the following versions were found for syft
0.1.0a1
0.1.1a2
0.1.2a1
0.1.3a1
0.1.4a1
0.1.4a2
0.1.5a1
0.1.6a1
0.1.7a1
0.1.8a1
0.1.9a1
0.1.10a1
0.1.10a2
0.1.10a4
0.1.11a1
0.1.12a1
0.1.13a1
0.1.14a1
0.1.15a1
0.1.16a1
0.1.19a1
0.1.20a1
0.1.21a1
0.1.22a1
0.1.23a1
0.1.24a1
0.1.25a1
0.1.26a1
0.1.27a1
0.1.28a1
0.1.29a1
0.2.0a1
0.2.0a2
Using 0.2.0a2
Use --version to specify a different version.
Using url https://files.pythonhosted.org/packages/97/ba/c01bb914f395611034bab10cb8d1d22e49691534d30f85efbd82f7bd27cf/syft-0.2.0a2.tar.gz (206 KB) for syft.
Downloading syft
PyPI URL:  https://files.pythonhosted.org/packages/97/ba/c01bb914f395611034bab10cb8d1d22e49691534d30f85efbd82f7bd27cf/syft-0.2.0a2.tar.gz
Using cached download
Unpacking syft...
done
working in /tmp/tmpw4b_esxkconda_skeleton_syft-0.2.0a2.tar.gz
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/user_name/anaconda3/conda-bld/skeleton_1579056804767/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main               
    ca-certificates:  2019.11.27-0           
    certifi:          2019.11.28-py37_0      
    ld_impl_linux-64: 2.33.1-h53a641e_7      
    libedit:          3.1.20181209-hc058e9b_0
    libffi:           3.2.1-hd88cf55_4       
    libgcc-ng:        9.1.0-hdf63c60_0       
    libstdcxx-ng:     9.1.0-hdf63c60_0       
    ncurses:          6.1-he6710b0_1         
    openssl:          1.1.1d-h7b6447c_3      
    pip:              19.3.1-py37_0          
    python:           3.7.6-h0371630_2       
    pyyaml:           5.2-py37h7b6447c_0     
    readline:         7.0-h7b6447c_5         
    setuptools:       44.0.0-py37_0          
    sqlite:           3.30.1-h7b6447c_0      
    tk:               8.6.8-hbc83047_0       
    wheel:            0.33.6-py37_0          
    xz:               5.2.4-h14c3975_4       
    yaml:             0.1.7-had09818_2       
    zlib:             1.2.11-h7b6447c_3      

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Applying patch: '/tmp/tmpw4b_esxkconda_skeleton_syft-0.2.0a2.tar.gz/pypi-distutils.patch'
Trying to apply patch as-is
INFO:conda_build.source:Trying to apply patch as-is
INFO conda_build.source:apply_patch(596): Trying to apply patch as-is
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    core_reqs = read(os.path.join(REQ_DIR, "requirements.txt")).split("\n")
  File "setup.py", line 12, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpw4b_esxkconda_skeleton_syft-0.2.0a2.tar.gz/syft-0.2.0a2/pip-dep/requirements.txt'
$PYTHONPATH = /tmp/tmpw4b_esxkconda_skeleton_syft-0.2.0a2.tar.gz/syft-0.2.0a2

Leaving build/test directories:
  Work:
 /home/user_name/anaconda3/conda-bld/skeleton_1579056804767/work 
  Test:
 /home/user_name/anaconda3/conda-bld/skeleton_1579056804767/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/user_name/anaconda3/conda-bld/skeleton_1579056804767/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol 
  Build:
source activate  /home/user_name/anaconda3/conda-bld/skeleton_1579056804767/_build_env 


Error: command failed: /home/user_name/anaconda3/conda-bld/skeleton_1579056804767/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python setup.py install

```

**Comment by systemshift** [comment]
currently working to onboard syft to conda-forge and will be the maintainer on the following [fork](https://github.com/systemshift/staged-recipes/tree/syft).
I have edited the recipe [file](https://github.com/systemshift/staged-recipes/blob/syft/recipes/syft/meta.yaml) but left some comments and will continue to work on it.

but from the FAQ, I think I found the reason behind the error.
```

 7. When or why do I need to use `{{ PYTHON }} -m pip install . -vv`?**

This should be the default install line for most Python packages. This is preferable to `python setup.py` because it handles metadata in a `conda`-friendlier way.
```

**Comment by systemshift** [comment]
Currently the issue seems to be with testing on the build machine.
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=156069&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0

```
test:
  imports:
  # work on later
    - simplejson
    - simplejson.tests
```

If anyone knows what should replace the default template with please let me know.

**Comment by imskr** [comment]
I'm working on this!

**Comment by systemshift** [comment]
> I'm working on this!

So I currently have a branch on this https://github.com/conda-forge/staged-recipes/pull/10602
One package dependency is missing from the conda-forge repo. I have opened a new issue for the maintainer to include his package, and now have been waiting for it. https://github.com/data61/python-paillier/issues/81
The other missing package used to be syft-proto but I have included it to conda-forge.

**Comment by imskr** [comment]
@systemshift Anything I can help you with?

**Comment by systemshift** [comment]
@imskr right now we have to wait for the dependency maintainer to solve the license issue, but what I would like to know if someone could explain what is the exact license problem the maintainer is facing. 
I would just go and fix it upstream if I understood what is the problem.

**Comment by systemshift** [comment]
**update:**
This has been dependency whack a mole. Once I thought we just got all of our dependency tree on conda merged a few hours ago, turns out last month `aiortc` has been added, which is not on conda, so now we have to get _that_ on conda-forge.
