### ISSUE TITLE
ModuleNotFoundError: No module named 'syft_proto'

### ISSUE THREAD

**Issue by genekogan** [OpenMined/PySyft#2921]
I am attempting to install Syft on a Raspberry Pi 4 with Raspbian Buster (armv71). I've successfully compiled PyTorch 1.4 from [this wheel](https://github.com/sungjuGit/Pytorch-and-Vision-for-Raspberry-Pi-4B).

After pip installing syft, I got the same error with `importlib` [which is reported in this issue](https://github.com/OpenMined/PySyft/pull/2908), and as of writing this, was fixed and merged to master a few hours ago.

So I tried to install syft directly from the master branch (`pip3 install git+https://github.com/OpenMined/PySyft/`), but now I get this error:

```
$ python3 -c "import syft"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/syft/__init__.py", line 15, in <module>
    import syft.frameworks.torch.hook.hook_args
  File "/home/pi/.local/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 6, in <module>
    from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
  File "/home/pi/.local/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 13, in <module>
    from syft.frameworks.torch.tensors.interpreters.crt_precision import _moduli_for_fields
  File "/home/pi/.local/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/crt_precision.py", line 7, in <module>
    from syft.frameworks.torch.tensors.interpreters.precision import FixedPrecisionTensor
  File "/home/pi/.local/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/precision.py", line 4, in <module>
    from syft.frameworks.torch.tensors.interpreters.additive_shared import AdditiveSharingTensor
  File "/home/pi/.local/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/additive_shared.py", line 12, in <module>
    from syft_proto.frameworks.torch.tensors.interpreters.v1.additive_shared_pb2 import (
ModuleNotFoundError: No module named 'syft_proto'
```

Maybe this will be fixed when syft [adds PyTorch 1.4 support](https://github.com/OpenMined/PySyft/issues/2916) officially? Is there a way around this error?

**Comment by karlhigley** [comment]
Try `pip install syft-proto`. It should get installed with the other dependencies if you install with `python setup.py install`, so let us know if you did that and still ended up having this issue. Otherwise, I’m guessing it has to do with building from source, but not sure exactly why.

**Comment by genekogan** [comment]
Did that and now I get:

$ python3 -c "import syft"

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/syft/__init__.py", line 43, in <module>
    from syft.grid.private_grid import PrivateGridNetwork
  File "/home/pi/.local/lib/python3.7/site-packages/syft/grid/private_grid.py", line 11, in <module>
    from syft.workers.node_client import NodeClient
  File "/home/pi/.local/lib/python3.7/site-packages/syft/workers/node_client.py", line 7, in <module>
    from syft.serde import serialize
  File "/home/pi/.local/lib/python3.7/site-packages/syft/serde/__init__.py", line 1, in <module>
    from syft.serde.serde import *
  File "/home/pi/.local/lib/python3.7/site-packages/syft/serde/serde.py", line 12, in <module>
    from syft.serde import msgpack
  File "/home/pi/.local/lib/python3.7/site-packages/syft/serde/msgpack/__init__.py", line 1, in <module>
    from syft.serde.msgpack import serde
  File "/home/pi/.local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 81, in <module>
    from syft.serde.msgpack.torch_serde import MAP_TORCH_SIMPLIFIERS_AND_DETAILERS
  File "/home/pi/.local/lib/python3.7/site-packages/syft/serde/msgpack/torch_serde.py", line 297, in <module>
    torch._C.Function: (_simplify_script_module, _detail_script_module),
AttributeError: module 'torch._C' has no attribute 'Function'
```

Could this be an issue with PyTorch 1.4? I am using the [wheel found here](https://github.com/sungjuGit/Pytorch-and-Vision-for-Raspberry-Pi-4B). Haven't found an armv71 build for 1.3.

**Comment by genekogan** [comment]
Update: I just got it to work by switching PyTorch back to 1.3 using [this build](https://discuss.pytorch.org/t/pytorch-1-3-wheels-for-raspberry-pi-python-3-7/58580) and now it works, so the issue can be closed.  Possibly the above is something to look into for updating syft to PyTorch 1.4.

**Comment by karlhigley** [comment]
Yeah, there’s an open issue for Torch 1.4 compatibility, but 1.4 was just released so we haven’t resolved the issue yet.

**Comment by dzlab** [comment]
I'm having same issue on OSX/conda env, is the compatibility with 1.4 not yet resolved? do I need to downgrade pytorch to 1.3?

**Comment by ajnovice** [comment]
I also have the same issue.

**Comment by karlhigley** [comment]
@ajnovice What versions of Python, PySyft, syft-proto, and PyTorch are you using?
