### ISSUE TITLE
Worker is crashing with a ResponseSignatureError on LSTM forward

### ISSUE THREAD

**Issue by matthiaslau** [OpenMined/PySyft#2956]
**Describe the bug**
I am trying to do a federated learning using a Vanilla LSTM. When doing a forward step with the LSTM layer the worker is crashing with a syft.exceptions.ResponseSignatureError.

I work with a local grid setup using websocket worker.

Precondition:
To be able to test a LSTM in general we need to overwrite the nn.LSTM `check_input` function because of the problems with the size function as discussed here: https://github.com/OpenMined/PySyft/issues/2201. To reproduce this bug you could use this commit: https://github.com/matthiaslau/PySyft/commit/68e5da07b55923749f5f23e3c1fc2579aa282d2c.

Model used:
```
from syft.frameworks.torch.nn import LSTM

class TurbofanModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = LSTM(11, 256, batch_first=True)
        self.fc2 = nn.Dropout(0.5)
        self.fc3 = nn.Linear(256, 1)
        
    def forward(self, x):
        x, _ = self.fc1(x)
        x = x[:, -1, :]
        x = self.fc2(x)
        x = self.fc3(x)
        
        return x
```

Train function:
```
def train(model, device, data, labels, optimizer, criterion, epoch):
    model.train()
    
    epoch_total = epoch_total_size(data)

    running_loss = 0

    for i in range(len(data)):
        for j in range(len(data[i])):
            worker = data[i][j].location
            model.send(worker)
            
            optimizer.zero_grad()
            output = model(data[i][j])
            loss = criterion(output, labels[i][j])
            loss.backward()
            optimizer.step()
            
            model.get()
            loss = loss.get()
            
            running_loss += loss.item() * data[i][j].shape[0]

    epoch_loss = running_loss / epoch_total
    
    return epoch_loss
```

Within the forward step when executing `x, _ = self.fc1(x)` the worker fails with the following stacktrace:
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 660, in register_response
    assert attr not in ambiguous_functions
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 714, in register_tensor
    tensor.id = response_ids.pop(-1)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 457, in execute_command
    command_name, response, list(return_ids), self
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 672, in register_response
    new_response = register_response_function(response, response_ids=response_ids, owner=owner)
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 766, in <lambda>
    return lambda x, **kwargs: f(lambdas, x, **kwargs)
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 536, in four_fold
    lambdas[1](args[1], **kwargs),
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 744, in <lambda>
    else lambda i, **kwargs: register_tensor(i, **kwargs)
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 716, in register_tensor
    raise exceptions.ResponseSignatureError
syft.exceptions.ResponseSignatureError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "/Users/matti/dev/PyGrid/app/websocket/app/main/events/__init__.py", line 57, in socket_api
    response = route_requests(message)
  File "/Users/matti/dev/PyGrid/app/websocket/app/main/events/__init__.py", line 37, in route_requests
    return forward_binary_message(message)
  File "/Users/matti/dev/PyGrid/app/websocket/app/main/auth/__init__.py", line 60, in wrapped
    return f(*args, **kwargs)
  File "/Users/matti/dev/PyGrid/app/websocket/app/main/events/syft_events.py", line 27, in forward_binary_message
    decoded_response = current_user.worker._recv_msg(message)
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/virtual.py", line 10, in _recv_msg
    return self.recv_msg(message)
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 310, in recv_msg
    response = self._message_router[type(msg)](msg.contents)
  File "/opt/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 468, in execute_command
    raise ResponseSignatureError(new_ids)
syft.exceptions.ResponseSignatureError: [33958291306, 39952567350, 62734941999, 3352040541]
2020-01-23T11:19:34Z {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '59064', 'HTTP_HOST': '0.0.0.0:3000', (hidden keys: 25)} failed with ResponseSignatureError
```

**Versions:**
 - PySyft: current master
 - PyGrid: current master

**Comment by DanyEle** [comment]
The "ResponseSignatureError" is raised because the forward LSTM pass fails.

This occurs because the forward pass in an LSTM uses the tensor.size() method, which is not currently implemented in PySyft.

The same problem would occur for a GRU.

*Workaround* My personal workaround to this problem was using my own version of the size() method, which breaks some other features of PySyft though https://github.com/OpenMined/PySyft/pull/2343

*Clean solution* Override PyTorch's LSTM's forward pass and replace occurrences of the size method calls wit the 'dim' method/attribute, which is indeed supported in PySyft.

**Comment by matthiaslau** [comment]
I already use our existing PySyft implementation of the LSTM (`from syft.frameworks.torch.nn import LSTM`) which is overwriting the forward method without using `size()`: https://github.com/OpenMined/PySyft/blob/master/syft/frameworks/torch/nn/rnn.py#L205.

**Comment by iamtrask** [comment]
> I already use our existing PySyft implementation of the LSTM (`from syft.frameworks.torch.nn import LSTM`) which is overwriting the forward method without using `size()`: https://github.com/OpenMined/PySyft/blob/master/syft/frameworks/torch/nn/rnn.py#L205.

This seems like the right approach.

**Comment by DanyEle** [comment]
Then something else is failing within that method. Are you testing this on remote workers or virtual workers?

I noticed that some things do work on virtual workers, but do not work on remote workers. Perhaps this is one of those cases.

**Comment by matthiaslau** [comment]
> I work with a local grid setup using websocket worker.

Do you have an idea where to look, so what are those things failing on remote workers?

**Comment by DanyEle** [comment]
I remember getting the same error as you on remote websockets and opening an Issue: 

https://github.com/OpenMined/PySyft/issues/2202 . It should have been fixed @LaRiffle  ?

**Comment by DanyEle** [comment]
@matthiaslau  Do you need this to work strictly on remote websockets? I believe this should work on virtual sockets right now.  Can you please try?

**Comment by matthiaslau** [comment]
It is workin using VirtualWorkers, very slow, but working. But it won´t help as the goal is to use it with PyGrid. Any ideas why the ResponseSignatureError is thrown when using the websocket worker?

**Comment by DanyEle** [comment]
> It is workin using VirtualWorkers, very slow, but working. But it won´t help as the goal is to use it with PyGrid. Any ideas why the ResponseSignatureError is thrown when using the websocket worker?

Did you try to replicate the code snippet I posted in https://github.com/OpenMined/PySyft/issues/2202 using web workers? Are you still getting the same error I posted there?
