### ISSUE TITLE
Websocket Secure error SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by fermat97** [OpenMined/PySyft#3260]
I am running the old version of [websockets_mnist_parallel](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/advanced/websockets_mnist_parallel) example with `websocket secure`. It seems the initial handshake is fine but once computing the loss in `run_websocket_client.py` script, it produces the error:

> Traceback (most recent call last):
  File "asynchronous_federated_learning.py", line 124, in <module>
    asyncio.run(main(args,device))
  File "/miniconda3/envs/pysyft/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/miniconda3/envs/pysyft/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "asynchronous_federated_learning.py", line 65, in main
    for worker in worker_instances
  File "run_websocket_client.py", line 114, in fit_model_on_worker
    loss = await worker.async_fit(dataset_key="mnist", return_ids=[0])
  File "/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/websocket_client.py", line 149, in async_fit
    self.url, timeout=TIMEOUT_INTERVAL, max_size=None, ping_timeout=TIMEOUT_INTERVAL
  File "/miniconda3/envs/pysyft/lib/python3.7/site-packages/websockets/client.py", line 517, in __aenter__
    return await self
  File "/miniconda3/envs/pysyft/lib/python3.7/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/miniconda3/envs/pysyft/lib/python3.7/asyncio/base_events.py", line 985, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/miniconda3/envs/pysyft/lib/python3.7/asyncio/base_events.py", line 1013, in _create_connection_transport
    await waiter
  File "/miniconda3/envs/pysyft/lib/python3.7/asyncio/sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/miniconda3/envs/pysyft/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/miniconda3/envs/pysyft/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)

Just to note that I am using `PySyft 0.2.4` and `Python 3.7`.

**Comment by karlhigley** [comment]
Would something like [this](https://github.com/cloudfoundry-community/cf-python-client/issues/51#issuecomment-536428838) work to address that?

**Comment by fermat97** [comment]
Actually I am not sure. I followed the advise proposed to add the following code at the beginning of my code and it does not work:

```python 
import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context
``` 

I have also tried adding to the `WebsocketClientWorker`, but no success. Done the same thing with `WebsocketServerWorker` and no success either.

**Comment by fermat97** [comment]
I tried to manually give WebsocketClientWorker the cert file but I faced another error:

> ssl.SSLError: [SSL] called a function you should not call

@IonesioJunior did you try the `WebsocketClientWorker` and `WebsocketServerWorker` in `async` mode?

**Comment by fermat97** [comment]
I have done these changes and I think now it works. In the constructor of the class `WebsocketClientWorker` I add:

```Python
if self.secure:
    self.ssl_context = ssl._create_unverified_context()
```

and in the `async_fit` function, instead of:

```Python 
async with websockets.connect(
                    self.url, timeout=TIMEOUT_INTERVAL, max_size=None, ping_timeout=TIMEOUT_INTERVAL
            ) as websocket:
```
I add the `ssl=self.ssl_context` to have:

```Python 
async with websockets.connect(
                    self.url, timeout=TIMEOUT_INTERVAL, max_size=None, ping_timeout=TIMEOUT_INTERVAL,ssl=self.ssl_context
            ) as websocket:
```

**Comment by karlhigley** [comment]
Would be great to capture these changes in a PR somehow, so that anyone else running locally in secure mode doesn't hit the same problem. 👍

**Comment by fermat97** [comment]
@karlhigley Ok, I ll make the PR ready and submit it
