### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not PosixPath

### ISSUE THREAD

**Issue by durden62** [OpenMined/PySyft#3400]
Hey, can anybody please tell me what is the cause of this error while running start_websocket_servers.py ? is it because of using subprocess.py file in the anaconda path?

> shekhar$ python start_websocket_servers.py 
Starting server for Alice
Traceback (most recent call last):
  File "start_websocket_servers.py", line 17, in <module>
    subprocess.Popen(call_alice)
  File "/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not PosixPath

**Comment by durden62** [comment]
this error was there because due to whatsoever reason, in this python file, the interpreter was not able to load the path of the file  start_websocket_servers.py.

this cause of error got confirmed because of the realization that no matter what was the path value in this command FILE_PATH = Path(__file__).resolve().parents[4].joinpath("run_websocket_server.py”)  in the start_websocket_servers.py file, there was no change in the error output. so the solution what i did was that i hardcoded the path of the file run_websocket_server.py in the command like this:  call_alice = [python,  "run_websocket_server.py", "--port", "8777", "--id", "alice”]
instead of original 
[
FILE_PATH = Path(__file__).resolve().parents[4].joinpath("run_websocket_server.py")

call_alice = [python, FILE_PATH, "--port", "8777", "--id", "alice"]
]

this solved the problem .
