### ISSUE TITLE
ImportError: cannot import name 'OperationMessage'

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/PySyft#3440]
Not sure if this is something I will have to post in syft-proto or here. Either ways I will post in both. I installed syft-proto from source. 

`Traceback (most recent call last):
  File "run_websocket_client.py", line 10, in <module>
    import syft as sy
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/__init__.py", line 15, in <module>
    import syft.frameworks.torch.hook.hook_args
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook_args.py", line 6, in <module>
    from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 13, in <module>
    from syft.frameworks.torch.tensors.interpreters.crt_precision import _moduli_for_fields
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/crt_precision.py", line 7, in <module>
    from syft.frameworks.torch.tensors.interpreters.precision import FixedPrecisionTensor
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/precision.py", line 7, in <module>
    from syft.generic.pointers.multi_pointer import MultiPointerTensor
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/generic/pointers/multi_pointer.py", line 11, in <module>
    from syft.workers.base import BaseWorker
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/workers/base.py", line 21, in <module>
    from syft.generic.pointers.object_pointer import ObjectPointer
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/generic/pointers/object_pointer.py", line 15, in <module>
    from syft.messaging.message import ForceObjectDeleteMessage
  File "/Users/hrishikesh/opt/anaconda3/envs/py3_6_3/lib/python3.6/site-packages/syft/messaging/message.py", line 14, in <module>
    from syft_proto.messaging.v1.message_pb2 import OperationMessage as OperationMessagePB
ImportError: cannot import name 'OperationMessage'`

**Comment by kamathhrishi** [comment]
I was using incompatible syft-proto and PySyft versions.
