### ISSUE TITLE
FL grid tutorials not working

### ISSUE THREAD

**Issue by thiessl** [OpenMined/PySyft#3474]
**Describe the bug**
Currently, the FL MNIST [tutorial ](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/grid/federated_learning/mnist/Fed.Learning%20MNIST%20%5B%20Part-2%20%5D%20-%20Train%20a%20Model.ipynb) seems not to work for me.
The line "model.send(worker)" results in the following issue:

`
WARNING:syft.workers.websocket_client:Websocket connection closed (worker: Bob)
WARNING:syft.workers.websocket_client:Created new websocket connection
Traceback (most recent call last):
  File ".../app/examples/PyGridFLMNIST.py", line 160, in <module>
    train(epoch)
  File ".../app/examples/PyGridFLMNIST.py", line 146, in train
    model.send(worker)
  File "...\app\venv\lib\site-packages\syft\frameworks\torch\hook\hook.py", line 613, in module_send_
    p.send_(*dest, **kwargs)
  File "...\app\venv\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 563, in send_
    return self.send(*location, inplace=True, **kwargs)
  File "...\app\venv\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 475, in send
    garbage_collect_data=garbage_collect_data,
  File "...\app\venv\lib\site-packages\syft\workers\base.py", line 400, in send
    self.send_obj(obj, worker)
  File "...\app\venv\lib\site-packages\syft\workers\base.py", line 735, in send_obj
    return self.send_msg(ObjectMessage(obj), location)
  File "...\app\venv\lib\site-packages\syft\workers\base.py", line 290, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "...\app\venv\lib\site-packages\syft\workers\virtual.py", line 15, in _send_msg
    return location._recv_msg(message)
  File "...\app\venv\lib\site-packages\syft\workers\websocket_client.py", line 105, in _recv_msg
    "Websocket connection closed and creation of new connection failed."
RuntimeError: Websocket connection closed and creation of new connection failed.
Exception ignored in: <function ObjectPointer.__del__ at 0x00000255EE19EA68>
Traceback (most recent call last):
  File "...\app\venv\lib\site-packages\syft\generic\pointers\object_pointer.py", line 344, in __del__
  File "...\app\venv\lib\site-packages\syft\workers\base.py", line 290, in send_msg
  File "...\app\venv\lib\site-packages\syft\workers\virtual.py", line 15, in _send_msg
  File "...\app\venv\lib\site-packages\syft\workers\websocket_client.py", line 93, in _recv_msg
  File "...\app\venv\lib\site-packages\syft\workers\node_client.py", line 175, in _forward_to_websocket_server_worker
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 314, in recv
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 331, in recv_data
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 344, in recv_data_frame
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 378, in recv_frame
  File "...\app\venv\lib\site-packages\websocket\_abnf.py", line 361, in recv_frame
  File "...\app\venv\lib\site-packages\websocket\_abnf.py", line 309, in recv_header
  File "...\app\venv\lib\site-packages\websocket\_abnf.py", line 396, in recv_strict
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 453, in _recv
  File "...\app\venv\lib\site-packages\websocket\_socket.py", line 115, in recv
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
Exception ignored in: <function ObjectPointer.__del__ at 0x00000255EE19EA68>
Traceback (most recent call last):
  File "...\app\venv\lib\site-packages\syft\generic\pointers\object_pointer.py", line 344, in __del__
  File "...\app\venv\lib\site-packages\syft\workers\base.py", line 290, in send_msg
  File "...\app\venv\lib\site-packages\syft\workers\virtual.py", line 15, in _send_msg
  File "...\app\venv\lib\site-packages\syft\workers\websocket_client.py", line 93, in _recv_msg
  File "...\app\venv\lib\site-packages\syft\workers\node_client.py", line 174, in _forward_to_websocket_server_worker
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 285, in send_binary
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 253, in send
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 279, in send_frame
  File "...\app\venv\lib\site-packages\websocket\_core.py", line 449, in _send
  File "...\app\venv\lib\site-packages\websocket\_socket.py", line 135, in send
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

Process finished with exit code 1

`

My docker containers are up and running (based on pysyft 0.2.5; locally built containers). For e.g., this example the setting general works.
So, I don't know why the model cannot be sent in the federated learning training part.

Some additional trials:

However, as I currently found out, that all federated learning tutorials  (+ spam prediction) fails (with version 0.2.5) when it comes to "model.send(worker)"...
This is true for non grid tutorials as [this ](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/advanced/websockets_mnist) as well.
It turned out, when I switch back to 0.2.4 at least the latter tutorial worked (web sockets).
Trying the same approach for the pygrid examples (i.e., pulling latest images from dockerhub, which should be based on 0.2.4). I was running both grid tutorials (also with syft 0.2.4) and got the "RuntimeError: Websocket connection closed and creation of new connection failed." even earlier, i.e., in: "shared_x1 = tag_img[0].send(compute_nodes[0])"
So, I am currently not finding any working configuration for pygrid (FL) examples.

**To Reproduce**
1. run grid-node and grid-gateway container based on the newest (0.2.5) syft version. (build locally, since docker hub images are based on older versions I guess.)
2. run any of these [tutorials](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/grid/federated_learning): 
3. error is thrown in lines with "model.send(worker)".

**Expected behavior**
Successfully sending the model to the grid-nodes (worker) and run through the tutorial.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version syft 0.2.5

**Comment by jmaunon** [comment]
@thiessl , did you find the solution?. I have found (maybe) the same error. Could you paste the error from node_server? (not only the client)

**Comment by junrong1** [comment]
> 3\. send

I have the same problem, did u find any solutoins?

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
