### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by NeuZhangQiang** [OpenMined/PySyft#3774]
The connection error is reported in my computer. 

The code is very easy:
```
import torch
import syft
hook = syft.TorchHook(torch)

from syft.workers.websocket_client import WebsocketClientWorker

remote_client = WebsocketClientWorker(
                            host='localhost',
                            hook=hook,
                            id=2,
                            port=8181)
```
And the error is:
```
Traceback (most recent call last):
  File "E:/FederatedLearning/code/test/client.py", line 11, in <module>
    port=8181)
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\syft\workers\websocket_client.py", line 64, in __init__
    self.connect()
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\syft\workers\websocket_client.py", line 76, in connect
    self.ws = websocket.create_connection(**args_)
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\websocket\_core.py", line 515, in create_connection
    websock.connect(url, **options)
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\websocket\_core.py", line 223, in connect
    options.pop('socket', None))
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\websocket\_http.py", line 121, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\websocket\_http.py", line 201, in _open_socket
    raise err
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\websocket\_http.py", line 176, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061]  No connection could be made because the target machine actively refused it。
```
However, a test code for socket is OK:
```
import socket
import sys
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = socket.gethostname()
port = 9999
s.connect((host, port))
msg = s.recv(1024)
s.close()
print(msg.decode('utf-8'))
```

Then, I set the  socket.gethostname() to WebsocketClientWorker, and the code is:
```
import torch
import syft
import socket
hook = syft.TorchHook(torch)

from syft.workers.websocket_client import WebsocketClientWorker

remote_client = WebsocketClientWorker(
                            host=socket.gethostname(),
                            hook=hook,
                            id=2,
                            port=8181)
```
But the same error is reported.

How can I fixed this error?

**Comment by NeuZhangQiang** [comment]
Finally, I find the solution. 

Using socket, we must create the server firstly, and then create the client. Those, the following code should be run firstly:

```
import syft as sy
import os
import sys
import logging
import torch
hook = sy.TorchHook(torch)

from syft.workers.websocket_server import WebsocketServerWorker

server_worker  = WebsocketServerWorker(
                            host="localhost",
                            hook=hook,
                            id=0,
                            port=8182)

server_worker.start()  # Might need to interrupt with `CTRL-C` or some other means

```
Then, do not close it, and run the following code:

```
import torch
import syft
import socket
hook = syft.TorchHook(torch)

from syft.workers.websocket_client import WebsocketClientWorker

remote_client = WebsocketClientWorker(
                            host='localhost',
                            hook=hook,
                            id=2,
                            port=8182)
```
Then, it is OK.
