### ISSUE TITLE
[torch] Cannot set values at indices in a tensor

### ISSUE THREAD

**Issue by juharris** [OpenMined/PySyft#3825]
## Description
Code like:
```Python
t = torch.zeros((2, 3), dtype=torch.float)
indices = torch.rand_like(t) > 0.5
t[indices] = 1
```
is fine when not hooked but fails when Torch is hooked.

## How to Reproduce
```Python
import syft as sy
import torch


def set_indices():
	t = torch.zeros((2, 3), dtype=torch.float)
	indices = torch.rand_like(t) > 0.5
	t[indices] = 1
	print("Set indices")


# The first call works fine.
set_indices()
hook = sy.TorchHook(torch)
# This call fails.
set_indices()
```

```
Set indices
Traceback (most recent call last):
  File "code.py", line 16, in <module>
    set_indices()
  File "code.py", line 8, in set_indices
    t[indices] = 1
  File "[REDACTED]\lib\site-packages\syft\generic\frameworks\hook\hook.py", line 170, in overloaded_native_method
    raise route_method_exception(e, self, args, kwargs)
  File "[REDACTED]\lib\site-packages\syft\generic\frameworks\hook\hook.py", line 166, in overloaded_native_method
    response = method(*args, **kwargs)
IndexError: The shape of the mask [3] at index 0 does not match the shape of the indexed tensor [2, 3] at index 0
```

## Expected Behavior
Should be able to assign a value.

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.7.7
 - Package Manager Version: Anaconda
- syft==0.2.6 (Installed via Pip)

**Comment by juharris** [comment]
Can anyone advise on where to make the change the correct this?

**Comment by wak31415** [comment]
I encountered the same issue when using facenet-pytorch (https://github.com/timesler/facenet-pytorch). My code:
```python
from facenet_pytorch import MTCNN
from PIL import Image
import torch
import syft as sy

im = Image.open("example.jpg")
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

mtcnn = MTCNN(
    image_size=160, margin=0, min_face_size=20,
    thresholds=[0.6,0.7,0.7], factor=0.709, post_process=True,
    device=device, keep_all=True
)

# Calling this works fine
x_aligned = mtcnn(im)
hook = sy.TorchHook(torch)

# This call fails with an IndexError
x_aligned = mtcnn(im)
```
The error is
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-44b80875f4ab> in <module>
----> 1 x_aligned = mtcnn(images[0])

~/miniconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/miniconda3/envs/pysyft/lib/python3.7/site-packages/facenet_pytorch/models/mtcnn.py in forward(self, img, save_path, return_prob)
    245         # Detect faces
    246         with torch.no_grad():
--> 247             batch_boxes, batch_probs = self.detect(img)
    248 
    249         # Determine if a batch or single image was passed

~/miniconda3/envs/pysyft/lib/python3.7/site-packages/facenet_pytorch/models/mtcnn.py in detect(self, img, landmarks)
    352                 self.pnet, self.rnet, self.onet,
    353                 self.thresholds, self.factor,
--> 354                 self.device
    355             )
    356 

~/miniconda3/envs/pysyft/lib/python3.7/site-packages/facenet_pytorch/models/utils/detect_face.py in detect_face(imgs, minsize, pnet, rnet, onet, threshold, factor, device)
     73         reg, probs = pnet(im_data)
     74 
---> 75         boxes_scale, image_inds_scale = generateBoundingBox(reg, probs[:, 1], scale, threshold[0])
     76         boxes.append(boxes_scale)
     77         image_inds.append(image_inds_scale)

~/miniconda3/envs/pysyft/lib/python3.7/site-packages/facenet_pytorch/models/utils/detect_face.py in generateBoundingBox(reg, probs, scale, thresh)
    210     mask_inds = mask.nonzero()
    211     image_inds = mask_inds[:, 0]
--> 212     score = probs[mask]
    213     reg = reg[:, mask].permute(1, 0)
    214     bb = mask_inds[:, 1:].type(reg.dtype).flip(1)

~/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook.py in overloaded_native_method(self, *args, **kwargs)
    167                 except BaseException as e:
    168                     # we can make some errors more descriptive with this method
--> 169                     raise route_method_exception(e, self, args, kwargs)
    170 
    171             else:  # means that there is a wrapper to remove

~/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook.py in overloaded_native_method(self, *args, **kwargs)
    163 
    164                 try:
--> 165                     response = method(*args, **kwargs)
    166 
    167                 except BaseException as e:

IndexError: The shape of the mask [111, 226] at index 0 does not match the shape of the indexed tensor [1, 111, 226] at index 0
```
and appears to be caused by the line `score = probs[mask]`, so I presume it is the same indexing issue.

**Comment by wak31415** [comment]
If there are technical reasons for why it is not possible, it would be nice to at least have a function which removes the hook from torch. That way one could arbitrarily switch between some standard (local) torch operations not supported by PySyft and some private operations on secretly shared data.
