### ISSUE TITLE
Error when using embeddings in a sy.Plan 

### ISSUE THREAD

**Issue by erksch** [OpenMined/PySyft#3854]
## Description
I have a super simple model that uses embeddings. 
But it always fails when I try to build the plan like in the guide "Part 08 - Introduction to Plans".

```python
import torch
import syft as sy
import torch.nn as nn

hook = sy.TorchHook(torch)
hook.local_worker.is_client_worker = False

class Net(sy.Plan):
    def __init__(self):
        super(Net, self).__init__()
        self.embedding = nn.Embedding(5, 20)
        self.fc1 = nn.Linear(20, 3)

    def forward(self, x):
        x = self.embedding(x)
        x = self.fc1(x)
        return x

x = torch.tensor([1, 2, 3, 4], dtype=torch.long)

model = Net()
model.build(x)
``` 

I get the following error message

```
UserWarning: Failed to translate Plan with PlanTranslatorTorchscript: Traceback (most recent call last):
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 341, in handle_func_command
    cmd, args_, kwargs_, return_args_type=True
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 157, in unwrap_args_from_function
    new_args = hook_args(args_)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 356, in <lambda>
    return lambda x: f(lambdas, x)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 551, in five_fold
    lambdas[0](args_[0], **kwargs),
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook_args.py", line 331, in <lambda>
    else lambda i: forward_func[type(i)](i)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 26, in <lambda>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 26, in <genexpr>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
syft.exceptions.PureFrameworkTensorFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/execution/plan.py", line 290, in build
    self.add_translation(translator)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/execution/plan.py", line 497, in add_translation
    role = plan_translator(self).translate()
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/execution/translation/torchscript.py", line 47, in translate
    torchscript_plan = jit.trace(wrap_stateful_plan, (*args, plan_params))
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/torch/jit/__init__.py", line 906, in trace
    _force_outplace)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/execution/translation/torchscript.py", line 43, in wrap_stateful_plan
    return translation_plan(*args[:-1])
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/execution/plan.py", line 381, in __call__
    result = self.role.execute()
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/execution/role.py", line 168, in execute
    self._execute_action(action)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/execution/role.py", line 227, in _execute_action
    response = method(*args_, **kwargs_)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook.py", line 340, in overloaded_func
    response = handle_func_command(command)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/execution/placeholder.py", line 67, in handle_func_command
    response = new_type.handle_func_command(new_command)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 384, in handle_func_command
    response = cls._get_response(cmd, args_, kwargs_)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 418, in _get_response
    response = command_method(*args_, **kwargs_)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook.py", line 340, in overloaded_func
    response = handle_func_command(command)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 384, in handle_func_command
    response = cls._get_response(cmd, args_, kwargs_)
  File "/home/erik/Projects/federated_ner/venv/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 418, in _get_response
    response = command_method(*args_, **kwargs_)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.FloatTensor instead (while checking arguments for embedding)

  f"Failed to translate Plan with {translator.__name__}: {traceback.format_exc()}"
```

## How to Reproduce
1. Run the code above.

## Expected Behavior
Should build the plan successfully.

## System Information
 - OS: Ubuntu 20.04
 - Language Version: Python 3.7
- Torch Version: 1.4.0
- Syft (Pip) Version: 0.2.6

**Comment by erksch** [comment]
Ping
