### ISSUE TITLE
Can not build training plan for LSTMs and RNNs 

### ISSUE THREAD

**Issue by MarcelSchmidberger** [OpenMined/PySyft#3858]
## Description
I would like to create a training plan for a model using an LSTM, but building the model fails with a `syft.exceptions.PureFrameworkTensorFoundError`.

``` python
import torch
import torch.nn.functional as F 
import torch.nn as nn
import syft as sy

hook = sy.TorchHook(torch)
hook.local_worker.is_client_worker = False

class Net(sy.Plan):
    def __init__(self):
        super(Net, self).__init__()
        #self.linear = nn.Linear(10, 20,2)
        self.lstm = nn.LSTM(10,20,2, bidirectional=True)

    def forward(self, x):
        #x = self.linear(x)
        x, _ = self.lstm(x)
        return x

model = Net()
model_build = model.build(torch.randn(5, 3, 10))
print(model_build)
```
will print on execution:

```
Traceback (most recent call last):
  File "lstm_test.py", line 25, in <module>
    model_build = model.build(torch.randn(5, 3, 10))
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/execution/plan.py", line 268, in build
    results = self.forward(*args, **framework_kwargs)
  File "lstm_test.py", line 21, in forward
    x, _ = self.lstm(x)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 559, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/generic/frameworks/hook/hook.py", line 336, in overloaded_func
    response = handle_func_command(command)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/execution/placeholder.py", line 61, in handle_func_command
    new_args, new_kwargs, new_type = hook_args.unwrap_args_from_function(cmd, args, kwargs)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/generic/frameworks/hook/hook_args.py", line 167, in unwrap_args_from_function
    new_args = args_hook_function(args_)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/generic/frameworks/hook/hook_args.py", line 356, in <lambda>
    return lambda x: f(lambdas, x)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/generic/frameworks/hook/hook_args.py", line 596, in many_fold
    return tuple(lambdas[i](args_[i], **kwargs) for i in range(len(lambdas)))
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/generic/frameworks/hook/hook_args.py", line 596, in <genexpr>
    return tuple(lambdas[i](args_[i], **kwargs) for i in range(len(lambdas)))
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/generic/frameworks/hook/hook_args.py", line 356, in <lambda>
    return lambda x: f(lambdas, x)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/generic/frameworks/hook/hook_args.py", line 529, in two_fold
    return lambdas[0](args_[0], **kwargs), lambdas[1](args_[1], **kwargs)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/generic/frameworks/hook/hook_args.py", line 331, in <lambda>
    else lambda i: forward_func[type(i)](i)
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/frameworks/torch/hook/hook_args.py", line 23, in <lambda>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
  File "/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/frameworks/torch/hook/hook_args.py", line 23, in <genexpr>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
syft.exceptions.PureFrameworkTensorFoundError

```
The above Error also occures when with a rnn instead of an lstm. When executing the model with a linear layer instead(see commented lines) you receive a `UserWarning: Failed to translate Plan with PlanTranslatorTfjs` but the model seems to be build just fine:

```
/home/marcel/Documents/Uni/susml/PySyft/venv/lib/python3.7/site-packages/syft-0.2.6-py3.7.egg/syft/execution/plan.py:291: UserWarning: Failed to translate Plan with PlanTranslatorTfjs
  warnings.warn(f"Failed to translate Plan with {translator.__name__}")
PlaceHolder[Id:56594233517]>tensor([[[ 0.5408,  0.0279, -0.9818,  0.2895,  0.1628, -0.6094, -0.5512,
          -0.6200, -0.2027,  0.7755, -0.5375,  0.7757,  1.5568,  0.9030,
          -1.2340, -0.4130, -0.0227, -0.1465,  0.7330, -0.4401],
         [ 0.9843, -0.1727, -0.2445, -0.2357,  0.1811, -0.4861, -0.8721,
          -0.1088,  0.6160,  0.4211,  0.0405, -0.2521,  1.1881,  0.5659,
          -0.7754, -0.1671, -0.5044,  0.5631,  0.5175, -0.6992],
         [-0.4118, -1.0496, -0.6354,  0.1261,  0.5838, -0.6802,  0.2162,
          -0.2929, -0.3710,  0.7294, -1.4893,  1.1834,  1.0034, -0.1837,
          -0.6342, -0.7577,  0.5907,  0.0542, -0.1588,  0.3000]],

        [[-0.2559, -0.4090, -0.0088, -0.0055, -0.6068, -0.5254,  0.1305,
           0.6405,  0.0095,  0.5856, -0.0463,  0.7301,  0.4374, -0.3811,
           0.5673,  0.1360, -0.4199,  0.2812,  0.2635, -0.0905],
         [ 0.3534,  0.0743, -0.2342, -0.0607,  0.1265,  0.5855, -0.0028,
           0.4698,  0.3866, -0.1411,  0.0183, -0.6274, -0.0413, -0.0765,
          -0.1766,  0.0630, -0.3791,  0.2553, -0.2885, -0.6911],
         [-0.3231,  0.1073,  0.2886,  0.0380, -0.8591,  0.4036,  1.0739,
           1.4278, -0.1034,  0.2123,  0.1819,  0.0864, -0.5612, -1.0153,
           1.5577,  0.4686, -1.0695,  0.0583, -0.3769, -0.3860]],

        [[ 0.4689, -0.3863,  0.3013, -0.3534,  0.1455,  0.2311, -1.1537,
           0.5043,  0.7206, -0.0928,  0.2761, -1.3805,  0.2971,  0.0132,
          -0.3988, -0.3448, -0.3475,  0.9968, -0.1489, -0.5611],
         [-0.2743, -0.9525, -0.5916, -0.1454,  0.0457, -0.4276,  0.5395,
           0.1007,  0.1638,  0.3508, -0.6358,  1.3194,  0.3267, -0.2033,
          -0.2467,  0.0923,  0.5002,  0.0901, -0.3728, -0.2128],
         [ 0.0742, -0.2314, -0.2106,  0.0084, -0.9181,  0.4651, -0.4287,
           0.7546,  0.0341,  0.1053,  0.6837,  0.2372, -0.3246,  0.2941,
          -0.5608,  0.5046,  0.0635,  0.3511, -0.4048, -1.6129]],

        [[-0.0754, -0.9962, -0.4718, -0.4694, -0.0676, -0.4839, -0.2061,
          -0.1574,  0.6376,  0.2058, -0.0710,  0.0563,  0.5647,  0.1623,
          -0.4661, -0.3370,  0.0375, -0.0835, -0.0738,  0.1677],
         [ 0.2598, -0.3529, -1.0836,  0.1934,  0.9282,  0.5626, -1.2716,
          -0.3943,  0.3610, -0.1451, -0.2788, -0.1611,  0.1835,  0.2327,
          -1.3609, -0.6935,  0.8280,  0.4100,  0.0816, -0.1162],
         [-1.0640, -1.2759,  0.0031, -0.0672,  0.4109,  0.2697, -0.0651,
           0.3960, -0.0489,  0.1541, -0.8572, -0.7205, -0.3251, -1.1119,
           0.1093, -1.1446, -0.0260, -0.1494, -0.4044,  0.9235]],

        [[-0.0045, -0.4398, -0.7853,  0.4165,  0.5881,  0.5512, -0.6292,
          -0.1111, -0.1936,  0.3538, -0.5263, -0.0382, -0.0644, -0.2640,
          -1.0816, -0.7356, -0.0607, -0.3764,  0.4034, -0.3205],
         [ 0.0339, -0.0897,  0.2296,  0.3543, -0.7847, -0.5072, -0.7024,
           0.8864, -0.4683,  0.8240,  0.0042,  1.0988,  0.7233,  0.0245,
          -0.0103,  0.3539, -0.0145,  1.1577,  0.3353, -1.1591],
         [-0.0356, -0.3060, -0.3521, -0.1169,  0.2116,  0.3646, -0.2458,
           0.3355,  0.4066, -0.1363, -0.0955, -0.4508,  0.0156, -0.2376,
          -0.0258, -0.2978,  0.0395,  0.3659, -0.3257,  0.0358]]],
       grad_fn=<AddBackward0>)

```
Is the building for LSTMs and RNNs implemented yet? I could not find any examples where a model with LSTM is actually being built, just some, where it is sent to virtual workers.
Your help would be highly appreciated

## How to Reproduce

Run the above code in the venv set up according to the pysft install guide.

## Expected Behavior
All kinds of Pytorch network layers work.

## System Information
 - OS: Ubuntu 19.10
 - Language Version: Python 3.7.5
 - Syft (Pip) Version: 0.2.6

**Comment by santteegt** [comment]
I'm trying to implement a Plan for an LSTM model built from scratch but I'm getting the following error at line 71 in my code: `TypeError: addmm(): argument 'mat1' (position 2) must be Tensor, not AutogradTensor`. If I remove the `trace_autograd=True` parameter on the `@sy.func2plan` decorator, a `PureFrameworkTensorFoundError` is being raised when trying to execute a `F.linear(input, self.weight, self.bias)`. Here's the source code of my implementation:

```python
class LSTMCell(nn.Module):
    """
    Python implementation of LSTMCell for MPC
    This class overrides the torch.nn.LSTMCell
    """
​
    def __init__(self, input_size, hidden_size, bias=True, nonlinearity=None):
        super(LSTMCell, self).__init__()
    
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.bias = bias
        self.nonlinearity = nonlinearity
​
​
        # Input Gate
        self.fc_xi = nn.Linear(input_size, hidden_size, bias=bias)
        self.fc_hi = nn.Linear(hidden_size, hidden_size, bias=bias)
        
        # Forget Gate
        self.fc_xf = nn.Linear(input_size, hidden_size, bias=bias)
        self.fc_hf = nn.Linear(hidden_size, hidden_size, bias=bias)
​
        # Cell Gate
        self.fc_xc = nn.Linear(input_size, hidden_size, bias=bias)
        self.fc_hc = nn.Linear(hidden_size, hidden_size, bias=bias)
​
        # Output Gate
        self.fc_xo = nn.Linear(input_size, hidden_size, bias=bias)
        self.fc_ho = nn.Linear(hidden_size, hidden_size, bias=bias)
        
        self.init_parameters()
        
    def init_parameters(self):
        std = 1.0 / np.sqrt(self.hidden_size)
        for w in self.parameters():
            w.data.uniform_(-std, std)
        ​
    def init_hidden(self, batch_size):
        return torch.zeros(batch_size, self.hidden_size)
​
    def forward(self, x, hc=None):
​
        if hc is None:
            batch_size = x.shape[1]
            hc = (self.init_hidden(batch_size), self.init_hidden(batch_size))
        h, c = hc
        
        print('LSTMCell', type(x), x.shape)
        print('Hidden', h, h.shape)
        print('C t-1', c, c.shape) 
        x_i = self.fc_xi(x)
        h_i = self.fc_hi(h)
        x_f = self.fc_xf(x)
        h_f = self.fc_hf(h)
        x_c = self.fc_xc(x)
        h_c = self.fc_hc(h)
        x_o = self.fc_xo(x)
        h_o = self.fc_ho(h)
        
        inputgate = (x_i + h_i).sigmoid()
        forgetgate = (x_f + h_f).sigmoid()
        cellgate = (x_c + h_c).tanh()
        outputgate = (x_o + h_o).sigmoid()
​
#         c_ = torch.mul(forgetgate, c) + torch.mul(inputgate, cellgate)
        c_ = (forgetgate * c) + (inputgate * cellgate)
​
#         h_ = torch.mul(outputgate, torch.tanh(c_))
        h_ = outputgate * c_.tanh()
​
        return h_, c_
​
​
class LSTM(nn.Module):
    """
    V2
    Python implementation of LSTM for MPC
    This class overrides the torch.nn.LSTM
    """
​
    def __init__(
        self,
        input_size,
        hidden_size,
        num_layers=1,
        bias=True,
        batch_first=False,
        dropout=0,
        bidirectional=False,
        nonlinearity=None,
    ):
        super(LSTM, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.bias = bias
        self.batch_first = batch_first
        self.dropout = float(dropout)
        self.bidirectional = bidirectional
#         self.num_directions = 2 if bidirectional else 1
#         self.is_lstm = base_cell is LSTMCell
        self.nonlinearity = nonlinearity
    
        # Dropout layers
        # TODO: implement a nn.Dropout class for PySyft
        # Link to issue: https://github.com/OpenMined/PySyft/issues/2500
​
        # Build RNN forward layers
        sizes = [input_size, *(hidden_size for _ in range(self.num_layers - 1))]
        self.rnn_forward = nn.ModuleList(
            (LSTMCell(sz, hidden_size, bias, nonlinearity) for sz in sizes)
        )
        
        self.lstm_cell = LSTMCell(self.input_size, self.hidden_size, self.bias, self.nonlinearity)
​
#         # Build RNN backward layers, if needed
#         if self.bidirectional:
#             self.rnn_backward = nn.ModuleList(
#                 (base_cell(sz, hidden_size, bias, nonlinearity) for sz in sizes)
#             )
​
    def init_hidden(self, batch_size):
        return torch.zeros(batch_size, self.hidden_size)
​
    def forward(self, x, hc=None):
        
        batch_size = x.shape[1]
        seq_len = x.shape[0]
        
        if hc is None:
            print('Init hc...')
            hc = (self.init_hidden(batch_size), self.init_hidden(batch_size))
            
        # Run through rnn in the forward direction
        for t in range(seq_len):
            input_ = x.select(0, t).view(1, -1)
            hc = self.lstm_cell(input_, hc)
                
        return hc
​
    
class WesadLSTM(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim=3, lstm_layers=1, dropout=0.2):
        # super(WesadLSTM, self).__init__(id="encrypted-model")
        super(WesadLSTM, self).__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.classes = output_dim
        self.lstm = LSTM(input_size=input_dim, hidden_size=input_dim, num_layers=lstm_layers, dropout=dropout)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)
​
    def forward(self, x, h):
        lstm_out, _ = self.lstm(x, h)
        out = self.fc(lstm_out.view(-1, self.hidden_dim))
        out = F.softmax(out.view(-1, self.classes), dim=1)
        return out
​
​
train_batch_size = 25
val_batch_size = 5
input_dim = 77
output_dim = 3
lstm_layers = 5
dropout = 0.5
lr = 1e-4
model = WesadLSTM(input_dim=input_dim, hidden_dim=input_dim, output_dim=output_dim, lstm_layers=lstm_layers,
                  dropout=dropout)
​
@sy.func2plan(args_shape=[(25, 77), (25, 3), (25, 77), (25, 77)], trace_autograd=True)
def try_batch(data, target, h, c):
    out = model(data, (h, c))
    
    batch_size = out.shape[0]
    loss = ((out - target)**2).sum().refresh()/batch_size
    loss.backward()
        
    return loss
```
