### ISSUE TITLE
Importing torchvision library is causing problems when using pysyft

### ISSUE THREAD

**Issue by usamazf** [OpenMined/PySyft#3886]
## Description
I use torchvision to load some datasets while using Pysyft framework, the problem is if I import the libraries after using "hook = sy.TorchHook(torch)" I get weird error. The issue disappears when doing import before using hook.

## How to Reproduce
1. Install latest Pysyft
2. write a simple script
3. import syft as sy
4. using torch hook
5. import torchvision

## Expected Behavior
To be able to load the library properly regardless of the order of being imported. I have requirement where I need to load datasets at a later time in a different module.

## System Information
 - OS: Ubuntu
 - OS Version: 16.04
 - Language Version: [e.g. Python 3.7, Node 10.18.1]

## Additional Context
Error trace is as follows:

```
Traceback (most recent call last):
  File "start_federated_server.py", line 19, in <module>
    import torchvision.transforms as transforms
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 14, in <module>
    from .roi_heads import RoIHeads
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torchvision/models/detection/roi_heads.py", line 211, in <module>
    @torch.jit.script
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/__init__.py", line 1281, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/_recursive.py", line 555, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/__init__.py", line 1281, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/_recursive.py", line 555, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/__init__.py", line 1278, in script
    ast = get_jit_def(obj)
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/frontend.py", line 171, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/frontend.py", line 212, in build_def
    build_stmts(ctx, body))
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/frontend.py", line 127, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/frontend.py", line 127, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/jit/frontend.py", line 186, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: import statements aren't supported:
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/frameworks/hook/hook.py", line 2471
    .. include:: cuda_deterministic_backward.rst
    """
    from .modules.utils import _ntuple
    ~~~~ <--- HERE

    def _check_size_scale_factor(dim):
'_onnx_heatmaps_to_keypoints' is being compiled since it was called from '_onnx_heatmaps_to_keypoints_loop'
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/torchvision/models/detection/roi_heads.py", line 218

    for i in range(int(rois.size(0))):
        xy_preds_i, end_scores_i = _onnx_heatmaps_to_keypoints(maps, maps[i],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                                                               widths_ceil[i], heights_ceil[i],
                                                               widths[i], heights[i],
```

**Comment by usamazf** [comment]
UPDATE: This error seems to occur only when I try to create plan using the tutorials at: [Creating Plans](examples/tutorials/static-fl/Part 01 - Create Plan.ipynbl). After removing any calls to @sy.func2plan() the code seems to work fine. Is this a bug or not? I am confused now even more!

**Comment by sug4ndh** [comment]
Can confirm this bug exists. I am not using any tutorial. Just created a hook and then tried to import datasets from torchvision and I got the same error.

The hack I am using right now is to do torchvision stuff first and then create a hook.

**Comment by thiessl** [comment]
Have this/similar problem too.
After hooking torch, the following code will fail every time:
`pickle.load(pickle_file)`

Are there any updates or workarounds on this?

`    return pickle.load(pickle_file)
  File "<project_folder>\venv\lib\site-packages\torchvision\__init__.py", line 3, in <module>
    from torchvision import models
  File "<project_folder>\venv\lib\site-packages\torchvision\models\__init__.py", line 12, in <module>
    from . import detection
  File "<project_folder>\venv\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "<project_folder>\venv\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 14, in <module>
    from .roi_heads import RoIHeads
  File "<project_folder>\venv\lib\site-packages\torchvision\models\detection\roi_heads.py", line 212, in <module>
    def _onnx_heatmaps_to_keypoints_loop(maps, rois, widths_ceil, heights_ceil,
  File "<project_folder>\venv\lib\site-packages\torch\jit\__init__.py", line 1281, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "<project_folder>\venv\lib\site-packages\torch\jit\_recursive.py", line 555, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "<project_folder>\venv\lib\site-packages\torch\jit\__init__.py", line 1281, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "<project_folder>\venv\lib\site-packages\torch\jit\_recursive.py", line 555, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "<project_folder>\venv\lib\site-packages\torch\jit\__init__.py", line 1278, in script
    ast = get_jit_def(obj)
  File "<project_folder>\venv\lib\site-packages\torch\jit\frontend.py", line 171, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "<project_folder>\venv\lib\site-packages\torch\jit\frontend.py", line 212, in build_def
    build_stmts(ctx, body))
  File "<project_folder>\venv\lib\site-packages\torch\jit\frontend.py", line 127, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "<project_folder>\venv\lib\site-packages\torch\jit\frontend.py", line 127, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "<project_folder>\venv\lib\site-packages\torch\jit\frontend.py", line 186, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: import statements aren't supported:
  File "<project_folder>\venv\lib\site-packages\syft-0.2.9-py3.8.egg\syft\generic\frameworks\hook\hook.py", line 2471
    .. include:: cuda_deterministic_backward.rst
    """
    from .modules.utils import _ntuple
    ~~~~ <--- HERE
    def _check_size_scale_factor(dim):
'_onnx_heatmaps_to_keypoints' is being compiled since it was called from '_onnx_heatmaps_to_keypoints_loop'
  File "<project_folder>\venv\lib\site-packages\torchvision\models\detection\roi_heads.py", line 218
    for i in range(int(rois.size(0))):
        xy_preds_i, end_scores_i = _onnx_heatmaps_to_keypoints(maps, maps[i],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                                                               widths_ceil[i], heights_ceil[i],
                                                               widths[i], heights[i],`

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
