### ISSUE TITLE
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_set_

### ISSUE THREAD

**Issue by Elvin10** [OpenMined/PySyft#3902]
RuntimeError when adding Batchnorm in the tutorial

differ from 
#[2498](https://github.com/OpenMined/PySyft/issues/2498) 
#[2132](https://github.com/OpenMined/PySyft/issues/2132)
I got a new problem:
Traceback (most recent call last):
  File "/home/ubuntu/liangenmin/Project/PySyft-master/mytest.py", line 117, in <module>
    train(args, model, device, federated_train_loader, optimizer, epoch)
  File "/home/ubuntu/liangenmin/Project/PySyft-master/mytest.py", line 84, in train
    model.get() # <-- NEW: get the model back
  File "/home/ubuntu/liangenmin/Project/PySyft-master/syft/frameworks/torch/hook/hook.py", line 671, in module_get_
    p.get_()
  File "/home/ubuntu/liangenmin/Project/PySyft-master/syft/frameworks/torch/tensors/interpreters/native.py", line 687, in get_
    return self.get(*args, inplace=True, **kwargs)
  File "/home/ubuntu/liangenmin/Project/PySyft-master/syft/frameworks/torch/tensors/interpreters/native.py", line 674, in get
    self.set_(tensor)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_set_

Process finished with exit code 1

Something wrong when model.get(), if I delete "to(device)", it works when I use cpu for data and model. It seems that type doesn't change in BN.
Here is my code:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

import syft as sy  # <-- NEW: import the Pysyft library
epochs = 10

hook = sy.TorchHook(torch)  # <-- NEW: hook PyTorch ie add extra functionalities to support Federated Learning
bob = sy.VirtualWorker(hook, id="bob")  # <-- NEW: define remote worker bob
alice = sy.VirtualWorker(hook, id="alice")

class Arguments():
    def __init__(self):
        self.batch_size = 64
        self.test_batch_size = 1000
        self.epochs = epochs
        self.lr = 0.01
        self.momentum = 0.5
        self.no_cuda = False
        self.seed = 1
        self.log_interval = 30
        self.save_model = False

args = Arguments()

use_cuda = not args.no_cuda and torch.cuda.is_available()

torch.manual_seed(args.seed)

device = torch.device("cuda" if use_cuda else "cpu")

kwargs = {'num_workers': 1, 'pin_memory': True} if use_cuda else {}

federated_train_loader = sy.FederatedDataLoader( # <-- this is now a FederatedDataLoader
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ]))
    .federate((bob, alice)), # <-- NEW: we distribute the dataset across all the workers, it's now a FederatedDataset
    batch_size=args.batch_size, shuffle=True, **kwargs)

test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=args.test_batch_size, shuffle=True, **kwargs)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4*4*50, 500)
        self.fc2 = nn.Linear(500, 10)
        self.bn1 = nn.BatchNorm2d(20)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.bn1(x)
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4*4*50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)


def train(args, model, device, federated_train_loader, optimizer, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(federated_train_loader): # <-- now it is a distributed dataset
        model.send(data.location) # <-- NEW: send the model to the right location
        data, target = data.to(device), target.to(device)
        # data, target = data.cuda(), target.cuda()
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        model.get() # <-- NEW: get the model back
        if batch_idx % args.log_interval == 0:
            loss = loss.get() # <-- NEW: get the loss back
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * args.batch_size, len(federated_train_loader) * args.batch_size,
                100. * batch_idx / len(federated_train_loader), loss.item()))


def test(args, model, device, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += F.nll_loss(output, target, reduction='sum').item() # sum up batch loss
            pred = output.argmax(1, keepdim=True) # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)

    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))

model = Net().to(device)
optimizer = optim.SGD(model.parameters(), lr=args.lr) # TODO momentum is not supported at the moment

for epoch in range(1, args.epochs + 1):
    train(args, model, device, federated_train_loader, optimizer, epoch)
    test(args, model, device, test_loader)

if (args.save_model):
    torch.save(model.state_dict(), "mnist_cnn.pt")
```

python 3.7.7
torch 1.4.0

**Comment by kouohhashi** [comment]
Hi, have you find a solution?

**Comment by Elvin10** [comment]
> Hi, have you find a solution?

Not yet, I have given up PySyft

**Comment by veronika98stephanie** [comment]
I got the same issue, is there any solution to this?

**Comment by cherry-licongyi** [comment]
I got the same issue, i'm feeling helpless
