### ISSUE TITLE
PointerTensor.share() on Websocket workers

### ISSUE THREAD

**Issue by zhangjinyiyi** [OpenMined/PySyft#4018]
## Question
Does PointerTensor.share(*workers) work for websocket worker? 

## Further Information
I am testing addiative sharing with websocker worker, but it seems not working. A client side sample code is provided below:
```
clientA = WebsocketClientWorker(id="a", host="0.0.0.0", port=8771, hook=hook, verbose=False)
clientB = WebsocketClientWorker(id="b", host="0.0.0.0", port=8772, hook=hook, verbose=False)

data_a = torch.tensor([2.5]).tag("data_a")
ptr_a = data_a.send(clientA, user="a")

data_b = torch.tensor([3.8]).tag("data_b")
ptr_b = data_b.send(clientB, user="b")

ptr_a_share = ptr_a.fix_precision().share(clientA, clientB)
ptr_b_share = ptr_b.fix_precision().share(clientA, clientB)
```
Error occurs during `.share()`. The sample code works for virtual workers.

The error message received on server side is 
```
Worker a couldn't recognize worker b
Worker me couldn't recognize worker b
Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/websocket_server.py:95> exception=AttributeError("'str' object has no attribute '_recv_msg'")>
Traceback (most recent call last):
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/base.py", line 327, in recv_msg
    response = self._message_router[type(msg)](msg)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/base.py", line 469, in execute_tensor_command
    return self.execute_computation_action(cmd.action)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/base.py", line 511, in execute_computation_action
    response = getattr(_self, op_name)(*args_, **kwargs_)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/frameworks/torch/tensors/interpreters/native.py", line 907, in share
    **kwargs_,
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/frameworks/torch/tensors/interpreters/precision.py", line 824, in share
    *owners, protocol=protocol, dtype=dtype, crypto_provider=crypto_provider, no_wrap=True
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/frameworks/torch/tensors/interpreters/native.py", line 922, in share
    .init_shares(*owners)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/frameworks/torch/tensors/interpreters/additive_shared.py", line 275, in init_shares
    share_ptr = share.send(owner, **no_wrap)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/frameworks/torch/tensors/interpreters/native.py", line 475, in send
    garbage_collect_data=garbage_collect_data,
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/base.py", line 400, in send
    self.send_obj(obj, worker)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/base.py", line 735, in send_obj
    return self.send_msg(ObjectMessage(obj), location)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/base.py", line 290, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "/Users/yi/anaconda3/envs/pysyft_0.2.5/lib/python3.7/site-packages/syft-0.2.5-py3.7.egg/syft/workers/virtual.py", line 15, in _send_msg
    return location._recv_msg(message)
AttributeError: 'str' object has no attribute '_recv_msg'
```

## System Information
 - OS: MacOS 
 - OS Version: 10.14.4
 - Language Version: Python 3.7.0, Pysyft 0.2.5

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
