### ISSUE TITLE
Error importing PySyft on MacOS after pip install

### ISSUE THREAD

**Issue by eliotpbrenner** [OpenMined/PySyft#4545]
## Description
Import syft results in error on Mac

## How to Reproduce
Follow instructions on installation on MacOS here:
https://github.com/OpenMined/PySyft/blob/master/INSTALLATION.md

## Expected Behavior
import syft to succeed.

## Error message

>>> import syft
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eliotpbrenner/Projects/PySyft/syft/__init__.py", line 43, in <module>
    from syft.grid.private_grid import PrivateGridNetwork  # noqa: E402,F401
  File "/Users/eliotpbrenner/Projects/PySyft/syft/grid/__init__.py", line 4, in <module>
    from syft.grid.rtc.network import Network
  File "/Users/eliotpbrenner/Projects/PySyft/syft/grid/rtc/network.py", line 6, in <module>
    from syft.grid.rtc.nodes_manager import WebRTCManager
  File "/Users/eliotpbrenner/Projects/PySyft/syft/grid/rtc/nodes_manager.py", line 1, in <module>
    from syft.grid.rtc.webrtc_connection import WebRTCConnection
  File "/Users/eliotpbrenner/Projects/PySyft/syft/grid/rtc/webrtc_connection.py", line 6, in <module>
    from aiortc import RTCPeerConnection, RTCSessionDescription
  File "/opt/miniconda3/envs/375/lib/python3.7/site-packages/aiortc/__init__.py", line 20, in <module>
    from .rtcpeerconnection import RTCPeerConnection
  File "/opt/miniconda3/envs/375/lib/python3.7/site-packages/aiortc/rtcpeerconnection.py", line 10, in <module>
    from .codecs import CODECS, HEADER_EXTENSIONS, is_rtx
  File "/opt/miniconda3/envs/375/lib/python3.7/site-packages/aiortc/codecs/__init__.py", line 15, in <module>
    from .opus import OpusDecoder, OpusEncoder
  File "/opt/miniconda3/envs/375/lib/python3.7/site-packages/aiortc/codecs/opus.py", line 9, in <module>
    from ._opus import ffi, lib
ImportError: dlopen(/opt/miniconda3/envs/375/lib/python3.7/site-packages/aiortc/codecs/_opus.abi3.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /opt/miniconda3/envs/375/lib/python3.7/site-packages/aiortc/codecs/_opus.abi3.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /opt/miniconda3/envs/375/lib/python3.7/site-packages/aiortc/codecs/_opus.abi3.so

## System Information
 - OS: MacOS
 - OS Version: 10.11.5
 - Language Version: Python 3.7.5
 - Package Manager Version: pip 20.2.1

**Comment by LaRiffle** [comment]
Hi!
I guess it must be linked to https://github.com/huggingface/tokenizers/issues/321#issuecomment-659969197
You're using macOS El Capitan from 2016, if you can upgrade to a newer version it will be fixed.
We should update `MACOSX_DEPLOYMENT_TARGET` as they suggest, but I don't know how to do this, contribution welcome  :)

**Comment by gmuraru** [comment]
@eliotpbrenner did @LaRiffle solved your issue?

**Comment by eliotpbrenner** [comment]
I trust that it'll work, but I didn't upgrade my MacOS.  I just decided to use PySyft on Unix.
