### ISSUE TITLE
I got problems while I'm executing "examples/tutorials/advanced/websockets_mnist/"

### ISSUE THREAD

**Issue by enebin** [OpenMined/PySyft#4579]
Hi, there.

While I was following the tutorial "examples/tutorials/advanced/websockets_mnist/", I got some problems and I'm here to ask one of those.

_Question is_ 
whenever I execute "start_websocket_servers.py" I get **"TypeError: argument of type 'WindowsPath' is not iterable"**
Is this related with FILE_PATH object?

For your convinience, I attached the codes and error messages below

```
import subprocess
import sys
from pathlib import Path

python = Path(sys.executable).name

FILE_PATH = Path(__file__).resolve().parent.joinpath("run_websocket_server.py")

call_alice = [python, FILE_PATH, "--port", "8777", "--id", "alice"]

call_bob = [python, FILE_PATH, "--port", "8778", "--id", "bob"]

call_charlie = [python, FILE_PATH, "--port", "8779", "--id", "charlie"]


print("Starting server for Alice")
subprocess.Popen(call_alice)

print("Starting server for Bob")
subprocess.Popen(call_bob)

print("Starting server for Charlie")
subprocess.Popen(call_charlie)

```

```
Traceback (most recent call last):
  File "C:/Users/Lee/Documents/GitHub/FED/websockets_mnist/start_websocket_servers.py", line 18, in <module>
    subprocess.Popen(call_alice)
  File "C:\Users\Lee\anaconda3\envs\websockets_mnist\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Lee\anaconda3\envs\websockets_mnist\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Lee\anaconda3\envs\websockets_mnist\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```

and honestly... I don't know where the "run_websocket_server.py" at "FILE_PATH" came from. I couldn't find it anywhere in this tutorial. Do I have to make this file on my own?

There are many other questions but that's the main one anyway. I guess I can do the rest myself after solving this one.

Thank you in advance!

**Comment by enebin** [comment]
I solved this problem by wrapping FILE_PATH with str() like below.
`FILE_PATH = str(Path(__file__).resolve().parent.joinpath("run_websocket_server.py"))`

I think it's not that elaborate way, but anyway it works for my case.
