### ISSUE TITLE
'IndexError: list index out of range' occurs whenever I try to do websocket connection.

### ISSUE THREAD

**Issue by enebin** [OpenMined/PySyft#4624]
## Description
Hi, I'm attempting to do federated learing tutorial using websocket communication. I used 2 Raspberry Pi 4 to do this. 

I followed the instructions written in here; https://blog.openmined.org/federated-learning-of-a-rnn-on-raspberry-pis,
but It threw an error. 

## How to Reproduce
I was using Docker env(arm32v7/python:3.7-slim) on Raspberry Pi 4s running **run_websocket_server.py** and central coordinator runs this notebook : https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/Federated%20Recurrent%20Neural%20Network.ipynb

First time, I used 
**python 3.7**
**run_websocket_server.py from branch 0.2.3a**(https://github.com/OpenMined/PySyft/blob/0.1.23a/examples/tutorials/advanced/websockets-example-MNIST/run_websocket_server.py)
**syft 0.1.13a**
**torch 1.0.0**
**torchvision 0.2.2.post3**

and this kind of error happened.

```2020-10-01 09:56:21,437 ERROR base_events.py(l:1619, p:26) - Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py:95> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/base.py", line 285, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 351, in deserialize
    return _detail(worker, simple_objects)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 543, in _detail
    return detailers[obj[0]](worker, obj[1])
IndexError: list index out of range
2020-10-01 09:56:21,674 ERROR base_events.py(l:1619, p:26) - Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py:95> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/base.py", line 285, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 351, in deserialize
    return _detail(worker, simple_objects)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 543, in _detail
    return detailers[obj[0]](worker, obj[1])
IndexError: list index out of range
2020-10-01 10:15:40,288 ERROR base_events.py(l:1619, p:26) - Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py:95> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/base.py", line 285, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 351, in deserialize
    return _detail(worker, simple_objects)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 543, in _detail
    return detailers[obj[0]](worker, obj[1])
IndexError: list index out of range
2020-10-01 10:15:40,513 ERROR base_events.py(l:1619, p:26) - Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py:95> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/base.py", line 285, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 351, in deserialize
    return _detail(worker, simple_objects)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 543, in _detail
    return detailers[obj[0]](worker, obj[1])
IndexError: list index out of range
```

Then second time, I used
**python 3.7**
**run_websocket_server.py from master branch**
**syft 0.2.3**
**torch 1.4.0**
**torchvision 0.5.0**

and similar error happened.
```
2020-10-05 04:29:26,743 ERROR base_events.py(l:1619, p:12) - Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py:95> exception=KeyError(53)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/base.py", line 309, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 69, in deserialize
    return strategy(binary, worker)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 369, in deserialize
    return _deserialize_msgpack_simple(simple_objects, worker)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 360, in _deserialize_msgpack_simple
    return _detail(worker, simple_objects)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 460, in _detail
    return detailers[obj[0]](worker, obj[1], **kwargs)
KeyError: 53
2020-10-05 04:29:26,972 ERROR base_events.py(l:1619, p:12) - Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py:95> exception=KeyError(53)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/usr/local/lib/python3.7/site-packages/syft/workers/base.py", line 309, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/serde.py", line 69, in deserialize
    return strategy(binary, worker)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 369, in deserialize
    return _deserialize_msgpack_simple(simple_objects, worker)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 360, in _deserialize_msgpack_simple
    return _detail(worker, simple_objects)
  File "/usr/local/lib/python3.7/site-packages/syft/serde/msgpack/serde.py", line 460, in _detail
    return detailers[obj[0]](worker, obj[1], **kwargs)
KeyError: 53
```

Error occurs right after the worker devices(RPi) receive a message from central device. Can you give me some advice about this situation?

+)
Error at the centeral deveice is like below
```
2020-10-05 16:01:10,413 WARNING websocket_client.py(l:107) - Websocket connection closed (worker: alice)
2020-10-05 16:01:10,537 WARNING websocket_client.py(l:112) - Created new websocket connection
Traceback (most recent call last):
  File "<file path...>/run_websocket_client(0.2.3).py", line 280, in <module>
    main()
  File "<file path...>/run_websocket_client(0.2.3).py", line 218, in main
    alice = WebsocketClientWorker(id="alice", port=10002, **a_kwargs_websocket)
  File "<virtual-env path...>\lib\site-packages\syft\workers\websocket_client.py", line 66, in __init__
    self.connect()
  File "<virtual-env path...>\lib\site-packages\syft\workers\websocket_client.py", line 79, in connect
    self._log_msgs_remote(self.log_msgs)
  File "<virtual-env path...>\lib\site-packages\syft\workers\websocket_client.py", line 145, in _log_msgs_remote
    return self._send_msg_and_deserialize("_log_msgs", value=value)
  File "<virtual-env path...>\lib\site-packages\syft\workers\websocket_client.py", line 126, in _send_msg_and_deserialize
    response = self._send_msg(serialized_message)
  File "<virtual-env path...>\lib\site-packages\syft\workers\websocket_client.py", line 93, in _send_msg
    return self._recv_msg(message)
  File "<virtual-env path...>\lib\site-packages\syft\workers\websocket_client.py", line 117, in _recv_msg
    "Websocket connection closed and creation of new connection failed."
RuntimeError: Websocket connection closed and creation of new connection failed.

Process finished with exit code 1
```

## Expected Behavior
When I tested it in local environment(without using RPis) It worked perfectly. 

## System Information
 - OS: Devian (Docker : https://hub.docker.com/r/arm32v7/python/)
 - Language Version:  Python 3.7
 - Package Manager Version: Written above

## Additional Context

I was filled with hope that it would be succesful, but after got this thing my heart's broken.... plz help me....

**Comment by gmuraru** [comment]
@IonesioJunior do you have any idea?

**Comment by sparkingdark** [comment]
Is it open to fix then I want to give a try

**Comment by gmuraru** [comment]
Sure! Assigned it to you @sparkingdark

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.

**Comment by sparkingdark** [comment]
Okay I will inform you soon... @cereallarceny and btw I am not on slack,can you send me a invite
