### ISSUE TITLE
Duet Network Exception

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4742]
## Description
This sometimes happens when using the MNIST notebooks, but doesn't seem to cause any issue. I guess there is a problem with the internal state sometimes and this exception isn't being caught.
```
Exception in callback Transaction.__retry()
handle: <TimerHandle when=156.343500133 Transaction.__retry()>
Traceback (most recent call last):
  File "/Users/madhavajay/.local/share/virtualenvs/PySyft-lHlz_cKe/lib/python3.8/site-packages/nest_asyncio.py", line 198, in run
    ctx.run(self._callback, *self._args)
  File "/Users/madhavajay/.local/share/virtualenvs/PySyft-lHlz_cKe/lib/python3.8/site-packages/aioice/stun.py", line 299, in __retry
    self.__future.set_exception(TransactionTimeout())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py", line 246, in set_exception
    raise exceptions.InvalidStateError(f'{self._state}: {self!r}')
asyncio.exceptions.InvalidStateError: FINISHED: <Future finished result=(Message(messa...\x8c\xe8\xd1'), ('192.168.176.153', 64677))>
```

## Definition of Done
Figure out how to repeat and setup exception handling to prevent this from displaying in the notebook.

**Comment by madhavajay** [comment]
Another similar one:
```
Task exception was never retrieved
future: <Task finished name='Task-47763' coro=<RTCSctpTransport._transmit() done, defined at /Users/madhavajay/.local/share/virtualenvs/PySyft-lHlz_cKe/lib/python3.8/site-packages/aiortc/rtcsctptransport.py:1505> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/Users/madhavajay/.local/share/virtualenvs/PySyft-lHlz_cKe/lib/python3.8/site-packages/aiortc/rtcsctptransport.py", line 1539, in _transmit
    await self._send_chunk(chunk)
  File "/Users/madhavajay/.local/share/virtualenvs/PySyft-lHlz_cKe/lib/python3.8/site-packages/aiortc/rtcsctptransport.py", line 1339, in _send_chunk
    await self.__transport._send_data(
  File "/Users/madhavajay/.local/share/virtualenvs/PySyft-lHlz_cKe/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 655, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
```
