### ISSUE TITLE
Syft logger generates error stack due to Unicode Emojis

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/PySyft#4904]
## Description
While testing the Duet MNIST tutorials with latest version of syft (dev branch) I ran into the following error:

```
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=207266), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'post_init', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 53, 'message': '> Creating ✉️  (RunFunctionOrConstructorAction) <UID:🚁🚃>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 68042, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 88-89: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=208269), 'exception': None, 'extra': {}, 'file': (name='client.py', path='e:\\repos\\pysyft\\src\\syft\\core\\node\\common\\client.py'), 'function': 'send_immediate_msg_without_reply', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 256, 'message': '> 📡 [🏰] Launcher Client (Duet)@<UID:🚉🚈> Signing ✉️  (RunFunctionOrConstructorAction) with 🝔', 'module': 'client', 'name': 'syft.core.node.common.client', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 69045, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4e1' in position 107: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=209268), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'sign', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 87, 'message': '> Signing with 🝔', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 70044, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f754' in position 87: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=212265), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'post_init', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 53, 'message': '> Creating Signed ✉️ 🔏 (SignedImmediateSyftMessageWithoutReply) <UID:🚁🚃>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 73041, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 95-96: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=213268), 'exception': None, 'extra': {}, 'file': (name='client.py', path='e:\\repos\\pysyft\\src\\syft\\core\\node\\common\\client.py'), 'function': 'send_immediate_msg_without_reply', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 258, 'message': '> Sending ✉️ 🔏 (SignedImmediateSyftMessageWithoutReply) 📡 [🏰] Launcher Client (Duet)@<UID:🚉🚈> ➡️  💠 [🏰] Launcher Client (Address)', 'module': 'client', 'name': 'syft.core.node.common.client', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 74044, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 115-116: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=213268), 'exception': None, 'extra': {}, 'file': (name='route.py', path='e:\\repos\\pysyft\\src\\syft\\core\\io\\route.py'), 'function': 'send_immediate_msg_without_reply', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 166, 'message': '> Routing ✉️ 🔏 (SignedImmediateSyftMessageWithoutReply) via 🛣️  (SoloRoute)', 'module': 'route', 'name': 'syft.core.io.route', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 74044, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 105-106: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=215267), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'post_init', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 53, 'message': '> Creating ✉️  (RequestMessage) <UID:🙾🜏>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 76043, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 88-89: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=216267), 'exception': None, 'extra': {}, 'file': (name='client.py', path='e:\\repos\\pysyft\\src\\syft\\core\\node\\common\\client.py'), 'function': 'send_immediate_msg_without_reply', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 256, 'message': '> 📡 [🏰] Launcher Client (Duet)@<UID:🚉🚈> Signing ✉️  (RequestMessage) with 🝔', 'module': 'client', 'name': 'syft.core.node.common.client', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 77043, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4e1' in position 107: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=217267), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'sign', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 87, 'message': '> Signing with 🝔', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 78043, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f754' in position 87: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=225268), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'post_init', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 53, 'message': '> Creating Signed ✉️ 🔏 (SignedImmediateSyftMessageWithoutReply) <UID:🙾🜏>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 86044, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 95-96: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=228265), 'exception': None, 'extra': {}, 'file': (name='client.py', path='e:\\repos\\pysyft\\src\\syft\\core\\node\\common\\client.py'), 'function': 'send_immediate_msg_without_reply', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 258, 'message': '> Sending ✉️ 🔏 (SignedImmediateSyftMessageWithoutReply) 📡 [🏰] Launcher Client (Duet)@<UID:🚉🚈> ➡️  💠 [🏰] Launcher Client (Address)', 'module': 'client', 'name': 'syft.core.node.common.client', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 89041, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 115-116: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=228265), 'exception': None, 'extra': {}, 'file': (name='route.py', path='e:\\repos\\pysyft\\src\\syft\\core\\io\\route.py'), 'function': 'send_immediate_msg_without_reply', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 166, 'message': '> Routing ✉️ 🔏 (SignedImmediateSyftMessageWithoutReply) via 🛣️  (SoloRoute)', 'module': 'route', 'name': 'syft.core.io.route', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 89041, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 105-106: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=344265), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'post_init', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 53, 'message': '> Creating ✉️  (RequestAnswerMessage) <UID:🚱🙔>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 205041, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 88-89: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=345265), 'exception': None, 'extra': {}, 'file': (name='client.py', path='e:\\repos\\pysyft\\src\\syft\\core\\node\\common\\client.py'), 'function': 'send_immediate_msg_with_reply', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 221, 'message': '> 📡 [🏰] Launcher Client (Duet)@<UID:🚉🚈> Signing ✉️  (RequestAnswerMessage) with 🝔', 'module': 'client', 'name': 'syft.core.node.common.client', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 206041, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4e1' in position 104: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=345265), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'sign', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 87, 'message': '> Signing with 🝔', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 206041, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f754' in position 87: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=349264), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'post_init', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 53, 'message': '> Creating Signed ✉️ 🔏 (SignedImmediateSyftMessageWithReply) <UID:🚱🙔>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 210040, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 95-96: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=354262), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': 'post_init', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 53, 'message': '> Creating ✉️  (RequestAnswerMessage) <UID:🚲🙖>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 215038, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 88-89: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=357264), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': '_object2proto', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 158, 'message': '> ✉️ 🔏 -> Proto 🔢 <UID: af8d7977a5014f1c80c2cfdfd18460e4>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 218040, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 84-85: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=361265), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': '_object2proto', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 158, 'message': '> ✉️ 🔏 -> Proto 🔢 <UID: fbefe4e6d0904fd881c439e3afbd02e5>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 222041, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 84-85: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=135, microseconds=364265), 'exception': None, 'extra': {}, 'file': (name='message.py', path='e:\\repos\\pysyft\\src\\syft\\core\\common\\message.py'), 'function': '_object2proto', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 158, 'message': '> ✉️ 🔏 -> Proto 🔢 <UID: 03f3d92ec8754f9896940b581539c15f>', 'module': 'message', 'name': 'syft.core.common.message', 'process': (id=24716, name='MainProcess'), 'thread': (id=11756, name='MainThread'), 'time': datetime(2020, 12, 11, 15, 38, 53, 225041, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time'))}
Traceback (most recent call last):
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
  File "C:\Users\test\.conda\envs\pysyft\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 84-85: character maps to <undefined>
--- End of logging error ---
```

### ⚠️ Note - The error (obviously) goes away if `sy.logging(file_path="./syft_do.log")` is commented out. 

I am taking a wild guess here but it seems the logger cannot handle some emojis.

## How to Reproduce
1. Run the MNIST example notebooks

## System Information
 - OS: Windows 10
 - Language Version: Python 3.8.5,
 - Syft Version - Syft Dev 0.3.0.post0.dev34+ga9a7874a

**Comment by madhavajay** [comment]
@jaintj95, this looks like its converting UTF-8 into cp1252 on windows and failing. Are you able to find the exact char sequence which fails and dump it do we can turn this into a test for all platforms and fix the issue?

**Comment by madhavajay** [comment]
This should be fixed.
