### ISSUE TITLE
RuntimeError: Could not infer dtype of ObjectWrapper

### ISSUE THREAD

**Issue by JacksonSung** [OpenMined/PySyft#6399]
Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/myconda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "src/client.py", line 126, in train_loop
    loss, sparse_sum = train(server, n_server, compress_ratio)
  File "src/client.py", line 194, in train
    loc_tensor = torch.tensor(train_model)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook.py", line 535, in new_tensor
    current_tensor = hook_self.torch.native_tensor(*args, **kwargs)
RuntimeError: Could not infer dtype of ObjectWrapper

First , I am so sorry to disturb you .secondly , I want to know how to convert ObjectWrapper to tensor ,or in any other ways  to get model.parameters . Last , thank you for your reply.

**Comment by JacksonSung** [comment]
no solving
