### ISSUE TITLE
Dev branch is failing to launch

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#7130]
Hagrid dev branch (commit 1042480ca16aaba31b36b33efc1e1c52d59ebf8e) is failing to launch.

1. pull dev
2. run "hagrid launch --dev --tail=True"
3. see error.

```
determined_bengios-celeryworker-1    |       Successfully uninstalled syft-0.7.0b59
determined_bengios-celeryworker-1    | Successfully installed syft-0.7.0b59
determined_bengios-celeryworker-1    | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
determined_bengios-backend-1         | Traceback (most recent call last):
determined_bengios-backend-1         |   File "/app/grid/backend_prestart.py", line 13, in <module>
determined_bengios-backend-1         |     from grid.db.session import get_db_session
determined_bengios-backend-1         |   File "/app/grid/db/session.py", line 12, in <module>
determined_bengios-backend-1         |     from grid.db.base import Base
determined_bengios-backend-1         |   File "/app/grid/db/base.py", line 2, in <module>
determined_bengios-backend-1         |     from syft.core.node.common.node_table import Base  # noqa
determined_bengios-backend-1         | ModuleNotFoundError: No module named 'syft.core'
determined_bengios-backend-1 exited with code 1
determined_bengios-celeryworker-1    | Traceback (most recent call last):
determined_bengios-celeryworker-1    |   File "/app/grid/backend_prestart.py", line 13, in <module>
determined_bengios-celeryworker-1    |     from grid.db.session import get_db_session
determined_bengios-celeryworker-1    |   File "/app/grid/db/session.py", line 12, in <module>
determined_bengios-celeryworker-1    |     from grid.db.base import Base
determined_bengios-celeryworker-1    |   File "/app/grid/db/base.py", line 2, in <module>
determined_bengios-celeryworker-1    |     from syft.core.node.common.node_table import Base  # noqa
determined_bengios-celeryworker-1    | ModuleNotFoundError: No module named 'syft.core'
determined_bengios-celeryworker-1 exited with code 1
determined_bengios-backend_stream-1  | INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
determined_bengios-backend-1         | Obtaining file:///app/syft
determined_bengios-backend-1         |   Installing build dependencies: started
determined_bengios-celeryworker-1    | Obtaining file:///app/syft
determined_bengios-celeryworker-1    |   Installing build dependencies: started
```

**Comment by iamtrask** [comment]
All tests passed in the latest PR: https://github.com/OpenMined/PySyft/pull/7126

**Comment by iamtrask** [comment]
I'm running the latest Docker and I ran Clean / Purge immediately before.

**Comment by iamtrask** [comment]
These are the images i'm running

<img width="746" alt="Screenshot 2022-11-29 at 17 28 19" src="https://user-images.githubusercontent.com/4328594/204600020-3f29a6da-905a-49f4-82ef-103db6ab0b76.png">

**Comment by madhavajay** [comment]
@iamtrask working great for me. Are you able to share more info about your hagrid?

This is mine right now:

```
 hagrid launch --dev --tail=True
✅ Docker service is running
✅ Git 2.38.1
✅ Docker 20.10.21
✅ Docker Compose 2.12.2

Launching a PyGrid Domain node on port 8081!

  - NAME: determined_altman
  - RELEASE: development
  - TYPE: domain
  - DOCKER_TAG: 0.7.0-beta.59-dev
  - GIT_HASH: 1042480ca16aaba31b36b33efc1e1c52d59ebf8e
  - HAGRID_VERSION: 0.2.113-dev
  - HAGRID_REPO_SHA: 1042480ca16aaba31b36b33efc1e1c52d59ebf8e
  - PORT: 8081
  - DOCKER COMPOSE: v2.12.2
```

**Comment by iamtrask** [comment]
Here's a clue - when my dev builds syft it installs a slightly different version.

```

quirky_gardner-celeryworker-1    | Successfully installed GitPython-3.1.29 asttokens-2.2.0 backcall-0.2.0 bandit-1.7.4 beautifulsoup4-4.11.1 black-22.6.0 black-nb-0.7 bleach-5.0.1 cfgv-3.3.1 coverage-6.5.0 defusedxml-0.7.1 distlib-0.3.6 doc8-0.11.2 docutils-0.19 dparse-0.6.2 entrypoints-0.4 exceptiongroup-1.0.4 execnet-1.9.0 executing-1.2.0 faker-13.15.1 fastjsonschema-2.16.2 filelock-3.8.0 flake8-3.8.4 gitdb-4.0.10 identify-2.5.9 importlib-metadata-4.13.0 iniconfig-1.1.1 ipython-8.7.0 isort-5.10.1 jedi-0.18.2 jinja2-3.1.2 jsonschema-4.17.3 jupyter-client-7.4.7 jupyter-core-5.1.0 jupyterlab-pygments-0.2.2 lxml-4.9.1 matplotlib-inline-0.1.6 mccabe-0.6.1 mistune-0.8.4 mypy-0.971 mypy-extensions-0.4.3 nbclient-0.7.2 nbconvert-6.5.4 nbformat-5.4.0 nest-asyncio-1.5.6 nodeenv-1.7.0 opentelemetry-api-1.11.1 opentelemetry-exporter-jaeger-1.11.1 opentelemetry-exporter-jaeger-proto-grpc-1.11.1 opentelemetry-exporter-jaeger-thrift-1.11.1 opentelemetry-sdk-1.11.1 opentelemetry-semantic-conventions-0.30b1 pandocfilters-1.5.0 parso-0.8.3 pathspec-0.10.2 pbr-5.11.0 pexpect-4.8.0 pickleshare-0.7.5 platformdirs-2.5.4 pluggy-1.0.0 pre-commit-2.20.0 ptyprocess-0.7.0 pure-eval-0.2.2 py-cpuinfo-9.0.0 pycodestyle-2.6.0 pyflakes-2.2.0 pyrsistent-0.19.2 pytest-7.2.0 pytest-asyncio-0.20.2 pytest-benchmark-4.0.0 pytest-cov-4.0.0 pytest-custom-exit-code-0.3.0 pytest-randomly-3.12.0 pytest-sugar-0.9.6 pytest-xdist-3.0.2 restructuredtext-lint-1.4.0 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.7 safety-2.1.1 smmap-5.0.0 soupsieve-2.3.2.post1 stack-data-0.6.2 stevedore-4.1.1 syft-0.7.0b59 thrift-0.16.0 tinycss2-1.2.1 tokenize-rt-5.0.0 tomli-2.0.1 tornado-6.2 traitlets-5.6.0 virtualenv-20.17.0 webencodings-0.5.1
```

**Comment by iamtrask** [comment]
Recloning now i've got
```
Launching a PyGrid Domain node on port 8081!

  - NAME: magical_larochelle
  - RELEASE: development
  - TYPE: domain
  - DOCKER_TAG: 0.7.0-beta.59-dev
  - GIT_HASH: c30667ea78e29a0f026b779e95d8f8c2f5222970
  - HAGRID_VERSION: 0.2.113-dev
  - HAGRID_REPO_SHA: c30667ea78e29a0f026b779e95d8f8c2f5222970
  - PORT: 8081
  - DOCKER COMPOSE: v2.12.2
```

**Comment by iamtrask** [comment]
Recloning fixed the issue - looks like I had some untracked changes in my files.
