### ISSUE TITLE
Broken "Lesson 2: Remote Data Science Demo"

### ISSUE THREAD

**Issue by dmpiergiacomo** [OpenMined/PySyft#7407]
## Description
Hi everyone, I am experiencing an issue withe **Lesson 2: Remote Data Science Demo**. When I execute:
```
from time import sleep
total_cases = 0
for result in results:
    ptr = result.publish()
    sleep(1)
    total_cases += ptr.get()
```
I receive the error:
```
Unable to Get Object with ID <UID: 754c48210cbc4ec9931f4be5be4f3f58> from store. Possible dangling Pointer. 'Object not found! for UID: 754c4821-0cbc-4ec9-931f-4be5be4f3f58'
```

## How to Reproduce
1. Run the notebook [Lesson 2: Remote Data Science Demo](https://github.com/OpenMined/courses/blob/introduction-to-remote-data-science-dev/L2_Demo.ipynb)
2. The error is thrown by the last code block

## Expected Behavior
After a long wait I receive the error:
```
Unable to Get Object with ID <UID: 754c48210cbc4ec9931f4be5be4f3f58> from store. Possible dangling Pointer. 'Object not found! for UID: 754c4821-0cbc-4ec9-931f-4be5be4f3f58'
```

## System Information
- Syft version 0.7.0 

## Additional Context
The problem persists after running the commands `hagrid land all; hagrid clean volumes;` followed by running again the Jupyter Notebook [Lesson 2: Remote Data Science Demo](https://github.com/OpenMined/courses/blob/introduction-to-remote-data-science-dev/L2_Demo.ipynb)

**Comment by dmpiergiacomo** [comment]
Following the suggestion of @madhavajay on Slack I an `docker logs -f yourdomain-celeryworker-1` to inspect the logs of the celeryworker container. Below te output:
```
[2023-03-06 18:36:32,171: INFO/MainProcess] Task grid.worker.msg_without_reply[a879cf0d-b805-430a-84e0-0fb3e34b1272] received
[2023-03-06 18:36:32,187: WARNING/MainProcess] Publish_id: 
[2023-03-06 18:36:32,187: WARNING/MainProcess]  
[2023-03-06 18:36:32,187: WARNING/MainProcess] <UID: bbace75459dc4065a8c0b0ed9dbdf0d7>
[2023-03-06 18:36:32,248: WARNING/MainProcess] Failed to get data from proxy object can only concatenate str (not "Int") to str.
[2023-03-06T18:36:32.248775+0000][CRITICAL][logger]][89] Unable to Get Object with ID <UID: bbace75459dc4065a8c0b0ed9dbdf0d7> from store. Possible dangling Pointer. can only concatenate str (not "Int") to str
[2023-03-06 18:36:32,277: ERROR/MainProcess] Task grid.worker.msg_without_reply[a879cf0d-b805-430a-84e0-0fb3e34b1272] raised unexpected: Exception('Unable to Get Object with ID <UID: bbace75459dc4065a8c0b0ed9dbdf0d7> from store. Possible dangling Pointer. can only concatenate str (not "Int") to str')
Traceback (most recent call last):
  File "/app/syft/src/syft/core/node/common/node_service/publish/publish_service.py", line 41, in process
    publish_object = retrieve_object(
  File "/app/syft/src/syft/core/node/common/action/greenlets_switch.py", line 20, in retrieve_object
    store_obj = node.store.get_or_none(key=id_at_location, proxy_only=proxy_only)
  File "/app/syft/src/syft/core/node/common/node_manager/redis_store.py", line 48, in get_or_none
    return self.get(key, proxy_only)
  File "/app/syft/src/syft/core/node/common/node_manager/redis_store.py", line 110, in get
    obj = self.resolve_proxy_object(obj=obj)
  File "/app/syft/src/syft/core/node/common/node_manager/redis_store.py", line 92, in resolve_proxy_object
    obj = obj.get_s3_data(settings=self.settings)
  File "/app/syft/src/syft/core/store/proxy_dataset.py", line 106, in get_s3_data
    raise e
  File "/app/syft/src/syft/core/store/proxy_dataset.py", line 99, in get_s3_data
    response = s3_client.get_object(Bucket=self.node_id.no_dash, Key=self.name)
  File "/app/syft/src/syft/core/store/proxy_dataset.py", line 87, in name
    return self.dataset_name + "/" + self.asset_name
TypeError: can only concatenate str (not "Int") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/grid/worker.py", line 32, in msg_without_reply
    raise e
  File "/app/grid/worker.py", line 30, in msg_without_reply
    node.recv_immediate_msg_without_reply(msg=obj_msg)
  File "/app/syft/src/syft/core/node/common/node.py", line 554, in recv_immediate_msg_without_reply
    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)
  File "/app/syft/src/syft/core/node/common/node.py", line 668, in process_message
    raise e
  File "/app/syft/src/syft/core/node/common/node.py", line 644, in process_message
    result = service.process(
  File "/app/syft/src/syft/core/node/common/node_service/publish/publish_service.py", line 76, in process
    traceback_and_raise(Exception(log))
  File "/app/syft/src/syft/logger.py", line 70, in traceback_and_raise
    raise e
Exception: Unable to Get Object with ID <UID: bbace75459dc4065a8c0b0ed9dbdf0d7> from store. Possible dangling Pointer. can only concatenate str (not "Int") to str
```

**Comment by dmpiergiacomo** [comment]
It seems that notebooks L3 and L5 (L5 being the one where `.publish()` and `.get()` are used) both work. I don't plan do debug further this issue at the moment, but I share below some observations.

It seems that when the DataSubject name is something like `"Country 0"` everything works fine, but when it is simply `"0"` you receive the error Exception: `Unable to Get Object with ID <UID: bbace75459dc4065a8c0b0ed9dbdf0d7> from store. Possible dangling Pointer. can only concatenate str (not "Int") to str`. Perhaps the `"0"` is converted into the integer `0` somewhere in one of the calls.

**Comment by madhavajay** [comment]
@dmpiergiacomo thanks for the bug report, the Data Subject system has changed a few times and this is no doubt the cause of the issue. Since L2 notebooks werent tested in CI it must have been missed. We have a more advanced Data Subject Registry in our new release which does not have this problem, it should be available at the end of Q1 along with tested notebooks on how to use it. :) Thanks for your patience.

**Comment by YasMinSdt** [comment]
> It seems that notebooks L3 and L5 (L5 being the one where `.publish()` and `.get()` are used) both work. I don't plan do debug further this issue at the moment, but I share below some observations.
> 
> It seems that when the DataSubject name is something like `"Country 0"` everything works fine, but when it is simply `"0"` you receive the error Exception: `Unable to Get Object with ID <UID: bbace75459dc4065a8c0b0ed9dbdf0d7> from store. Possible dangling Pointer. can only concatenate str (not "Int") to str`. Perhaps the `"0"` is converted into the integer `0` somewhere in one of the calls.

I've tried it with a string like "person 0" but still get the same error. Have you found a solution?

**Comment by Terror-1** [comment]
> ## Description
> Hi everyone, I am experiencing an issue withe **Lesson 2: Remote Data Science Demo**. When I execute:
> 
> ```
> from time import sleep
> total_cases = 0
> for result in results:
>     ptr = result.publish()
>     sleep(1)
>     total_cases += ptr.get()
> ```
> 
> I receive the error:
> 
> ```
> Unable to Get Object with ID <UID: 754c48210cbc4ec9931f4be5be4f3f58> from store. Possible dangling Pointer. 'Object not found! for UID: 754c4821-0cbc-4ec9-931f-4be5be4f3f58'
> ```
> 
> ## How to Reproduce
> 1. Run the notebook [Lesson 2: Remote Data Science Demo](https://github.com/OpenMined/courses/blob/introduction-to-remote-data-science-dev/L2_Demo.ipynb)
> 2. The error is thrown by the last code block
> 
> ## Expected Behavior
> After a long wait I receive the error:
> 
> ```
> Unable to Get Object with ID <UID: 754c48210cbc4ec9931f4be5be4f3f58> from store. Possible dangling Pointer. 'Object not found! for UID: 754c4821-0cbc-4ec9-931f-4be5be4f3f58'
> ```
> 
> ## System Information
> * Syft version 0.7.0
> 
> ## Additional Context
> The problem persists after running the commands `hagrid land all; hagrid clean volumes;` followed by running again the Jupyter Notebook [Lesson 2: Remote Data Science Demo](https://github.com/OpenMined/courses/blob/introduction-to-remote-data-science-dev/L2_Demo.ipynb)

DId you find a solution to this problem ?

**Comment by madhavajay** [comment]
We will be creating new tutorials to replace these but for now the Lessons which are tested in CI lessons 3 onwards do work.
