### ISSUE TITLE
Tensor.publish got 'GAMMA_TENSOR_OP' object has no attribute '_object2proto'

### ISSUE THREAD

**Issue by mathews** [OpenMined/PySyft#7444]
## Description
Tensor.publish(sigma=3) got 'GAMMA_TENSOR_OP' object has no attribute '_object2proto' in the celery worker backend.

I use docker compose to startup the backend, the 0.7.0 stable release is used.
client code were run with the exact python package version as the pysyft backend, python 3.10.6 was used to run client code.

[2023-03-21 02:59:43,196: ERROR/MainProcess] Task grid.worker.msg_without_reply[826a7a61-f10b-4a64-bb80-861457acf251] raised unexpected: AttributeError("'GAMMA_TENSOR_OP' object has no attribute '_object2proto'")
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/grid/worker.py", line 32, in msg_without_reply
    raise e
  File "/app/grid/worker.py", line 30, in msg_without_reply
    node.recv_immediate_msg_without_reply(msg=obj_msg)
  File "/app/syft/src/syft/core/node/common/node.py", line 554, in recv_immediate_msg_without_reply
    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)
  File "/app/syft/src/syft/core/node/common/node.py", line 668, in process_message
    raise e
  File "/app/syft/src/syft/core/node/common/node.py", line 644, in process_message
    result = service.process(
  File "/app/syft/src/syft/core/node/common/node_service/object_action/obj_action_service.py", line 27, in process
    msg.execute_action(node=node, verify_key=verify_key)
  File "/app/syft/src/syft/core/node/common/action/run_class_method_action.py", line 292, in execute_action
    node.store[self.id_at_location] = result
  File "/app/syft/src/syft/core/node/common/node_manager/redis_store.py", line 152, in __setitem__
    self.set(key=key, value=value)
  File "/app/syft/src/syft/core/node/common/node_manager/redis_store.py", line 162, in set
    bin = serialize(value.data, to_bytes=True)
  File "/app/syft/src/syft/core/common/serde/serialize.py", line 77, in _serialize
    return validate_type(is_serializable._object2bytes(), bytes)
  File "/app/syft/src/syft/core/tensor/tensor.py", line 635, in _object2bytes
    chunk_bytes(serialize(self.child, to_bytes=True), "child", tensor_msg)  # type: ignore
  File "/app/syft/src/syft/core/common/serde/serialize.py", line 77, in _serialize
    return validate_type(is_serializable._object2bytes(), bytes)
  File "/app/syft/src/syft/core/tensor/autodp/gamma_tensor.py", line 2718, in _object2bytes
    gamma_msg.jaxOp = serialize(self.jax_op, to_bytes=True)
  File "/app/syft/src/syft/core/common/serde/serialize.py", line 83, in _serialize
    serialized_data = is_serializable._object2proto().SerializeToString()
  File "/app/syft/src/syft/core/common/serde/recursive.py", line 34, in rs_object2proto
    msg.fields_data.append(serialize(field_obj, to_bytes=True))
  File "/app/syft/src/syft/core/common/serde/serialize.py", line 83, in _serialize
    serialized_data = is_serializable._object2proto().SerializeToString()
AttributeError: 'GAMMA_TENSOR_OP' object has no attribute '_object2proto'

## Expected Behavior
publish api just does not work.

## System Information
 - OS: [ubuntu]
 - OS Version: [20.04]
 - Language Version: Python 3.10
- docker 23.0.1

**Comment by madhavajay** [comment]
@mathews what version of syft is this for? Sounds like 0.6 or 0.7?

**Comment by madhavajay** [comment]
Closing for now.
