### ISSUE TITLE
Error occurred while running hagrid quickstart

### ISSUE THREAD

**Issue by Kariten** [OpenMined/PySyft#7630]
## Description
While running the command “hagrid quickstart”, the following error comes out.

## Screenshots
![image](https://github.com/OpenMined/PySyft/assets/40301904/61a292ff-07d3-4507-9529-cb32d7061b62)

## System Information
 - OS: Ubuntu 22.04
 - Language Version: Python 3.10.6
 - HAGRID_VERSION: 0.3.8
 - Syft version: 0.8.1b

## Additional Context
The full output of the error:

(1, b'', 'packaging')
Error running quickstart: (1, b'', 'packaging')
Traceback (most recent call last):
  File "/home/pysyft1/.local/lib/python3.10/site-packages/virtualenvapi/manage.py", line 228, in install
    self._execute_pip(['install'] + package_args + options)
  File "/home/pysyft1/.local/lib/python3.10/site-packages/virtualenvapi/manage.py", line 132, in _execute_pip
    return self._execute(exec_args, log=log)
  File "/home/pysyft1/.local/lib/python3.10/site-packages/virtualenvapi/manage.py", line 156, in _execute
    raise e
  File "/home/pysyft1/.local/lib/python3.10/site-packages/virtualenvapi/manage.py", line 145, in _execute
    raise subprocess.CalledProcessError(returncode, proc, (output, error))
subprocess.CalledProcessError: Command '<Popen: returncode: 1 args: ['bin/python', '-m', 'pip', '--disable-pip-versi...>' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pysyft1/.local/bin/hagrid", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/pysyft1/.local/lib/python3.10/site-packages/hagrid/cli.py", line 3703, in quickstart_cli
    return run_quickstart(
  File "/home/pysyft1/.local/lib/python3.10/site-packages/hagrid/cli.py", line 3638, in run_quickstart
    raise e
  File "/home/pysyft1/.local/lib/python3.10/site-packages/hagrid/cli.py", line 3505, in run_quickstart
    quickstart_setup(
  File "/home/pysyft1/.local/lib/python3.10/site-packages/hagrid/cli.py", line 3822, in quickstart_setup
    raise e
  File "/home/pysyft1/.local/lib/python3.10/site-packages/hagrid/cli.py", line 3795, in quickstart_setup
    env.install("packaging", options=["-U"])
  File "/home/pysyft1/.local/lib/python3.10/site-packages/virtualenvapi/manage.py", line 230, in install
    raise PackageInstallationException((e.returncode, e.output, package))
virtualenvapi.exceptions.PackageInstallationException: (1, b'', 'packaging')

**Comment by madhavajay** [comment]
@Kariten can you run:
```
$ hagrid quickstart --reset
```

**Comment by Kariten** [comment]
> @Kariten can you run:
> 
> ```
> $ hagrid quickstart --reset
> ```

This works pretty well, thanks.
