### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by cherry-licongyi** [OpenMined/PySyft#8023]
## code:
```
                client_model.send(client_workers[client_i])
                for name, param in client_model.named_parameters():
                    print(param.location)
                    break
                    
                client_model.train()
                correct = 0
                train_loss = 0

                # Create optimizer for wrokers
                if self.pretrain_epochs == 150 or self.model_architecture == 'vgg16': #use smaller lr in random noise
                    client_optimizer = torch.optim.SGD(params=client_model.parameters(), lr=0.01)
                else:
                    client_optimizer = torch.optim.SGD(params=client_model.parameters(), lr=0.1) #0.1

                for local_epoch in range(self.training_ops.local_epoch):
                    for data, target in federated_train_loader[client_i]:
                        print(data.location)
                        if self.use_cuda:
                            data, target = data.cuda(), target.cuda()
                        print(data.shape)    
                        client_optimizer.zero_grad()
                        output = client_model(data)
```

## output:
```
<VirtualWorker id:client_0 #objects:12>
<VirtualWorker id:client_0 #objects:14>
torch.Size([1, 1, 28, 28])

Traceback (most recent call last):
  File "main.py", line 154, in <module>
    main(config, args.experiment, args.generate_watermark, args.patching_type)
  File "main.py", line 52, in main
    exp)
  File "main.py", line 71, in experiment_training
    federated_model, scores = agent.federated_train(log_interval=1000)
  File "/home/hjw/lcy/WAFFLE-main/src/experiment.py", line 372, in federated_train
    output = client_model(data)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hjw/lcy/WAFFLE-main/src/Network.py", line 139, in forward
    out = self.block(x)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook.py", line 717, in overloaded_func
    response = TorchTensor.handle_func_command(command)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 270, in handle_func_command
    response = new_type.handle_func_command(new_command)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/pointers/object_pointer.py", line 88, in handle_func_command
    response = owner.send_command(location, command)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 427, in send_command
    ret_val = self.send_msg(codes.MSGTYPE.CMD, message, location=recipient)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 223, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/virtual.py", line 10, in _send_msg
    return location._recv_msg(message)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/virtual.py", line 13, in _recv_msg
    return self.recv_msg(message)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 254, in recv_msg
    response = self._message_router[msg_type](contents)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 385, in execute_command
    response = command(*args, **kwargs)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook.py", line 717, in overloaded_func
    response = TorchTensor.handle_func_command(command)
  File "/home/hjw/lcy/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 287, in handle_func_command
    response = eval(cmd)(*args, **kwargs)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

## version
torch 1.4.0
cuda 12.2

**Comment by madhavajay** [comment]
Hi @cherry-licongyi `VirtualWorker` was in `0.2.x` which is deprecated, however we will be adding GPU / CUDA support to `0.8.x` soon.
