### ISSUE TITLE
Connection issue between different servers

### ISSUE THREAD

**Issue by lokeaichirou** [OpenMined/PySyft#8095]
## Description
Hi guys,
When I run gateway, data owner and data scientist on different servers, I had the problem in log in the data scientist account (that is registered as guest client in data owner side ) in data scientist side.  Before I try log in, I retrieve the data owner  node by using

data_owner_nodes   = data_scientist_root_client.peers[0].guest_client.domains.retrieve_nodes()[:-1]

, this step works, but it fails at step of

data_scientist_accounts_in_data_owner_domain = [domain_node.guest_client.login(email="sheldon@caltech.edu", password="changethis") for domain_node in data_owner_nodes]

Traceback (most recent call last):
  File "/home/llimou/inria_tests/202309_FL/data_scientist.py", line 61, in <module>
    data_scientist_accounts_in_data_owner_domain = [domain_node.guest_client.login(email="[sheldon@caltech.edu](mailto:sheldon@caltech.edu)", password="changethis") for domain_node in data_owner_nodes]
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/inria_tests/202309_FL/data_scientist.py", line 61, in <listcomp>
    data_scientist_accounts_in_data_owner_domain = [domain_node.guest_client.login(email="[sheldon@caltech.edu](mailto:sheldon@caltech.edu)", password="changethis") for domain_node in data_owner_nodes]
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/syft/service/network/node_peer.py", line 88, in guest_client
    return self.client_with_key(credentials=guest_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/syft/service/network/node_peer.py", line 79, in client_with_key
    client_type = connection.get_client_type()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/syft/client/client.py", line 297, in get_client_type
    metadata = self.get_node_metadata(credentials=SyftSigningKey.generate())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/syft/client/client.py", line 208, in get_node_metadata
    response = self._make_get(self.routes.ROUTE_METADATA.value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/syft/client/client.py", line 165, in _make_get
    response = self.session.get(
               ^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llimou/miniconda3/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=34403): Max retries exceeded with url: /api/v2/metadata (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f02f383ec10>: Failed to establish a new connection: [Errno 111] Connection refused'))

## How to Reproduce
Run codes for gateway, data owner and data scientist on different servers,

## Expected Behavior
Should log in the data scientist account (that is registered as guest client in data owner side ) in data scientist side.  

## System Information
 - OS: [linux]
 - OS Version: [Debian GNU/Linux 11 (bullseye)]
 - Language Version: [e.g. Python 3.9, ]
 - Package Manager Version: [conda 23.7.3]

**Comment by madhavajay** [comment]
@lokeaichirou did you provide a full publicly accessible url to the login command for each client. If one of the nodes needs to contact another you need to make sure they can reach those IPs as well, alternatively you can log in with a client and provide a new alternative `route` to one node for another node.
